
from test_engine import EngineInterface
from test_engine import minimax_value_list

def draw_board(game_state):
    for row in range(3):    
        print(" --- --- ---")
        for k in range(row*3,row*3+3):
            print("| ", end="")
            print(game_state[k], end=" ")
        print("|")
    print(" --- --- ---")

engine = EngineInterface(3)

game_states = []

a = ["X", "O", " "]
for i0 in a:
 for i1 in a:
  for i2 in a:
   for i3 in a:
    for i4 in a:
     for i5 in a:
      for i6 in a:
       for i7 in a:
        for i8 in a:
            p = [i0, i1, i2, i3, i4, i5, i6, i7, i8]

            if p.count("X") == p.count("O") or p.count("X") == p.count("O") + 1:
                if p.count(" ") > 0:
                     if not engine.three_in_a_row(p):
                             game_states.append(p)

def X_in_turn(game_state):
    """Return True iff there is an odd number of " " in game_state"""
    return len([i for i in game_state if i == " "]) % 2 == 1
    
def win_in_1(game_state):
    """Return if for example it's X's turn and X can make a three in a row."""    
    available_moves = [i for i in range(9) if game_state[i] == " "]                       
    # If X is in turn.
    if len(available_moves) % 2 == 1:
        for move in available_moves:
            game_state[move] = "X"
            if engine.three_in_a_row(game_state):
                return True                    
            game_state[move] = " "               
    # If O is in turn.
    else:
        for move in available_moves:
            game_state[move] = "O"
            if engine.three_in_a_row(game_state):
                return True                    
            game_state[move] = " "
    return False

# Print out a text that can be used for making an opening book.
for p in game_states:
    if p.count(" ") == 2: # This condition tells the number of empty positions
                          # in the game state.
        value_list = minimax_value_list(p)
        values = []
        positive_values = []
        negative_values = []
        for x in value_list:
            if x != None and x not in values:
                values.append(x)
                if x > 0:
                    positive_values.append(x)
                elif x < 0:
                    negative_values.append(x)
        if X_in_turn(p):
            best = max(values)
        else:
            best = min(values)
        moves = [move for move in range(9) if value_list[move] == best]
        game_state_string = "".join(p)
        print("'" + game_state_string + "': " + str(moves) + ",")
            
# The books give the best moves for each possible game state with 1, 2 etc
# moves made. Each of the given game states are equaly good, so for example if one is a
# win in a certain amount of plies, the rest is also a win in the same number of plies.

book1 = {
'X        ': [4],
' X       ': [0, 2, 4, 7],
'  X      ': [4],
'   X     ': [0, 4, 5, 6],
'    X    ': [0, 2, 6, 8],
'     X   ': [2, 3, 4, 8],
'      X  ': [4],
'       X ': [1, 4, 6, 8],
'        X': [4]}

book2 = {
'XO       ': [3, 4, 6],
'X O      ': [3, 6, 8],
'X  O     ': [1, 2, 4],
'X   O    ': [1, 2, 3, 5, 6, 7, 8],
'X    O   ': [2, 4, 6],
'X     O  ': [1, 2, 8],
'X      O ': [2, 4, 6],
'X       O': [2, 6],
'OX       ': [3, 4, 6, 8],
'O X      ': [5, 6, 8],
'O  X     ': [1, 2, 4, 8],
'O   X    ': [1, 2, 3, 5, 6, 7, 8],
'O    X   ': [2],
'O     X  ': [2, 7, 8],
'O      X ': [6],
'O       X': [2, 6],
' XO      ': [4, 5, 6, 8],
' X O     ': [0, 4],
' X  O    ': [0, 2, 3, 5, 6, 8],
' X   O   ': [2, 4],
' X    O  ': [0],
' X     O ': [0, 2, 3, 4, 5, 6, 8],
' X      O': [2],
' OX      ': [4, 5, 8],
' O X     ': [0, 4],
' O  X    ': [0, 2, 3, 5, 6, 8],
' O   X   ': [2, 4],
' O    X  ': [0, 4, 8],
' O     X ': [0, 2, 3, 4, 5, 6, 8],
' O      X': [2, 4, 6],
'  XO     ': [0, 4, 8],
'  X O    ': [0, 1, 3, 5, 6, 7, 8],
'  X  O   ': [0, 1, 4],
'  X   O  ': [0, 8],
'  X    O ': [0, 4, 8],
'  X     O': [0, 1, 6],
'  OX     ': [0],
'  O X    ': [0, 1, 3, 5, 6, 7, 8],
'  O  X   ': [0, 1, 4, 6],
'  O   X  ': [0, 8],
'  O    X ': [8],
'  O     X': [0, 6, 7],
'   XO    ': [0, 1, 2, 6, 7, 8],
'   X O   ': [0, 1, 2, 4, 6, 7, 8],
'   X  O  ': [2, 4, 7, 8],
'   X   O ': [4, 6],
'   X    O': [6],
'   OX    ': [0, 1, 2, 6, 7, 8],
'   O X   ': [0, 1, 2, 4, 6, 7, 8],
'   O  X  ': [4, 7, 8],
'   O   X ': [4, 6],
'   O    X': [2, 4, 6],
'    XO   ': [0, 1, 2, 6, 7, 8],
'    X O  ': [0, 1, 2, 3, 5, 7, 8],
'    X  O ': [0, 2, 3, 5, 6, 8],
'    X   O': [0, 1, 2, 3, 5, 6, 7],
'    OX   ': [0, 1, 2, 6, 7, 8],
'    O X  ': [0, 1, 2, 3, 5, 7, 8],
'    O  X ': [0, 2, 3, 5, 6, 8],
'    O   X': [0, 1, 2, 3, 5, 6, 7],
'     XO  ': [8],
'     X O ': [4, 8],
'     X  O': [0, 4, 6, 7],
'     OX  ': [0, 4, 8],
'     O X ': [4, 8],
'     O  X': [4, 6, 7],
'      XO ': [0, 3, 4],
'      X O': [0, 2, 3],
'      OX ': [0, 2, 3, 4],
'      O X': [0, 2, 5],
'       XO': [0, 2, 4, 5],
'       OX': [2, 4, 5]}

book3 = {
'XXO      ': [5, 8],
'XX O     ': [2],
'XX  O    ': [2],
'XX   O   ': [2],
'XX    O  ': [2],
'XX     O ': [2],
'XX      O': [2],
'XOX      ': [4],
'XO X     ': [6],
'XO  X    ': [8],
'XO   X   ': [4],
'XO    X  ': [3],
'XO     X ': [6, 8],
'XO      X': [4],
'X XO     ': [1],
'X X O    ': [1],
'X X  O   ': [1],
'X X   O  ': [1],
'X X    O ': [1],
'X X     O': [1],
'X OX     ': [6],
'X O X    ': [8],
'X O  X   ': [3, 4],
'X O   X  ': [3],
'X O    X ': [8],
'X O     X': [4],
'X  XO    ': [6],
'X  X O   ': [6],
'X  X  O  ': [7, 8],
'X  X   O ': [6],
'X  X    O': [6],
'X  OX    ': [8],
'X  O X   ': [2, 8],
'X  O  X  ': [4],
'X  O   X ': [4],
'X  O    X': [4],
'X   XO   ': [8],
'X   X O  ': [8],
'X   X  O ': [8],
'X   X   O': [2, 6],
'X   OX   ': [1, 2, 7, 8],
'X   O X  ': [3],
'X   O  X ': [3, 5, 6, 8],
'X   O   X': [1, 3, 5, 7],
'X    XO  ': [8],
'X    X O ': [4],
'X    X  O': [3, 4, 6],
'X    OX  ': [3],
'X    O X ': [4],
'X    O  X': [4],
'X     XO ': [3],
'X     X O': [3],
'X     OX ': [1, 4],
'X     O X': [4],
'X      XO': [1, 2, 4],
'X      OX': [4],
'OXX      ': [3, 6],
'OX X     ': [4, 5, 7],
'OX  X    ': [7],
'OX   X   ': [6],
'OX    X  ': [4, 7],
'OX     X ': [4],
'OX      X': [4, 6, 7],
'O XX     ': [4, 5],
'O X X    ': [6],
'O X  X   ': [8],
'O X   X  ': [4],
'O X    X ': [6],
'O X     X': [5],
'O  XX    ': [5],
'O  X X   ': [4],
'O  X  X  ': [1, 2],
'O  X   X ': [2],
'O  X    X': [2, 4, 5],
'O   XX   ': [3],
'O   X X  ': [2],
'O   X  X ': [1],
'O   X   X': [2, 6],
'O    XX  ': [2],
'O    X X ': [2, 6],
'O    X  X': [2],
'O     XX ': [8],
'O     X X': [7],
'O      XX': [6],
' XXO     ': [0],
' XX O    ': [0],
' XX  O   ': [0],
' XX   O  ': [0],
' XX    O ': [0],
' XX     O': [0],
' XOX     ': [8],
' XO X    ': [7],
' XO  X   ': [3, 4, 7],
' XO   X  ': [4, 7, 8],
' XO    X ': [4],
' XO     X': [4, 7],
' X XO    ': [0, 2, 6],
' X X O   ': [0, 6],
' X X  O  ': [8],
' X X   O ': [0, 2],
' X X    O': [2, 6],
' X OX    ': [7],
' X O X   ': [2, 8],
' X O  X  ': [4],
' X O   X ': [4],
' X O    X': [4],
' X  XO   ': [7],
' X  X O  ': [7],
' X  X  O ': [0, 2, 6, 8],
' X  X   O': [7],
' X  OX   ': [0, 2, 8],
' X  O X  ': [0, 2, 3, 5],
' X  O  X ': [0, 2, 3, 5, 6, 8],
' X  O   X': [0, 2, 3, 5],
' X   XO  ': [0, 8],
' X   X O ': [0, 2],
' X   X  O': [6],
' X   OX  ': [4],
' X   O X ': [4],
' X   O  X': [4],
' X    XO ': [0, 2],
' X    X O': [2],
' X    OX ': [4],
' X    O X': [0],
' X     XO': [4],
' X     OX': [0, 2],
' OXX     ': [4],
' OX X    ': [6],
' OX  X   ': [8],
' OX   X  ': [4],
' OX    X ': [6, 8],
' OX     X': [5],
' O XX    ': [5],
' O X X   ': [4],
' O X  X  ': [0],
' O X   X ': [6, 8],
' O X    X': [4],
' O  XX   ': [3],
' O  X X  ': [2],
' O  X  X ': [0, 2, 6, 8],
' O  X   X': [0],
' O   XX  ': [4],
' O   X X ': [6, 8],
' O   X  X': [2],
' O    XX ': [8],
' O    X X': [7],
' O     XX': [6],
'  XXO    ': [0, 1, 6, 7],
'  XX O   ': [0, 6],
'  XX  O  ': [4, 5, 8],
'  XX   O ': [4],
'  XX    O': [6],
'  XOX    ': [6],
'  XO X   ': [8],
'  XO  X  ': [4],
'  XO   X ': [4],
'  XO    X': [5],
'  X XO   ': [6],
'  X X O  ': [0, 8],
'  X X  O ': [6],
'  X X   O': [6],
'  X OX   ': [8],
'  X O X  ': [1, 3, 5, 7],
'  X O  X ': [3, 5, 6, 8],
'  X O   X': [5],
'  X  XO  ': [8],
'  X  X O ': [8],
'  X  X  O': [6, 7],
'  X  OX  ': [4],
'  X  O X ': [4],
'  X  O  X': [4],
'  X   XO ': [4],
'  X   X O': [4],
'  X   OX ': [0, 1, 4],
'  X   O X': [5],
'  X    XO': [1, 4],
'  X    OX': [5],
'  OXX    ': [5],
'  OX X   ': [4],
'  OX  X  ': [0],
'  OX   X ': [0, 8],
'  OX    X': [0],
'  O XX   ': [3],
'  O X X  ': [0, 8],
'  O X  X ': [1],
'  O X   X': [0],
'  O  XX  ': [0, 3, 4],
'  O  X X ': [0],
'  O  X  X': [0, 1],
'  O   XX ': [8],
'  O   X X': [7],
'  O    XX': [6],
'   XXO   ': [0, 2, 6, 8],
'   XX O  ': [5],
'   XX  O ': [5],
'   XX   O': [5],
'   XOX   ': [0, 1, 2, 6, 7, 8],
'   XO X  ': [0],
'   XO  X ': [0, 6, 8],
'   XO   X': [0, 1, 6, 7],
'   X XO  ': [4],
'   X X O ': [4],
'   X X  O': [4],
'   X OX  ': [0],
'   X O X ': [0, 6],
'   X O  X': [0, 6],
'   X  XO ': [0],
'   X  X O': [0],
'   X  OX ': [1, 4, 5],
'   X  O X': [4, 5],
'   X   XO': [2],
'   X   OX': [4],
'   OXX   ': [0, 2, 6, 8],
'   OX X  ': [2],
'   OX  X ': [1],
'   OX   X': [0],
'   O XX  ': [2, 8],
'   O X X ': [2, 8],
'   O X  X': [2],
'   O  XX ': [8],
'   O  X X': [7],
'   O   XX': [6],
'    XXO  ': [3],
'    XX O ': [3],
'    XX  O': [3],
'    XOX  ': [2],
'    XO X ': [1],
'    XO  X': [0],
'    X XO ': [2],
'    X X O': [2],
'    X OX ': [1],
'    X O X': [0],
'    X  XO': [1],
'    X  OX': [0],
'    OXX  ': [1, 2, 7, 8],
'    OX X ': [2, 6, 8],
'    OX  X': [2],
'    O XX ': [8],
'    O X X': [7],
'    O  XX': [6],
'     XXO ': [4],
'     XX O': [3, 4],
'     XOX ': [0],
'     XO X': [2],
'     X XO': [1, 3, 4],
'     X OX': [2],
'     OXX ': [8],
'     OX X': [7],
'     O XX': [6],
'      XXO': [2, 5],
'      XOX': [4],
'      OXX': [0, 3]}

book4 = {
'XXOO     ': [4],
'XXO O    ': [6],
'XXO  O   ': [8],
'XXO   O  ': [4],
'XXO    O ': [6, 8],
'XXO     O': [5],
'XX OO    ': [2],
'XX O O   ': [2],
'XX O  O  ': [2],
'XX O   O ': [2],
'XX O    O': [2],
'XX  OO   ': [2],
'XX  O O  ': [2],
'XX  O  O ': [2],
'XX  O   O': [2],
'XX   OO  ': [2],
'XX   O O ': [2],
'XX   O  O': [2],
'XX    OO ': [2],
'XX    O O': [2],
'XX     OO': [2],
'XOXO     ': [4, 8],
'XOX O    ': [7],
'XOX  O   ': [4, 6],
'XOX   O  ': [8],
'XOX    O ': [4],
'XOX     O': [6],
'XOOX     ': [6],
'XOO X    ': [8],
'XOO  X   ': [3, 4],
'XOO   X  ': [3],
'XOO    X ': [6, 8],
'XOO     X': [4],
'XO XO    ': [6],
'XO X O   ': [6],
'XO X  O  ': [4],
'XO X   O ': [6],
'XO X    O': [6],
'XO OX    ': [8],
'XO O X   ': [8],
'XO O  X  ': [4, 8],
'XO O   X ': [8],
'XO O    X': [4],
'XO  XO   ': [8],
'XO  X O  ': [8],
'XO  X  O ': [8],
'XO  X   O': [3, 6],
'XO  OX   ': [7],
'XO  O X  ': [3],
'XO  O  X ': [6],
'XO  O   X': [7],
'XO   XO  ': [4, 8],
'XO   X O ': [4],
'XO   X  O': [3],
'XO   OX  ': [3],
'XO   O X ': [6, 8],
'XO   O  X': [4],
'XO    XO ': [3],
'XO    X O': [3],
'XO    OX ': [2, 3, 4, 5, 8],
'XO    O X': [4],
'XO     XO': [2, 3, 4, 5, 6],
'XO     OX': [4],
'X XOO    ': [1],
'X XO O   ': [1],
'X XO  O  ': [1],
'X XO   O ': [1],
'X XO    O': [1],
'X X OO   ': [1],
'X X O O  ': [1],
'X X O  O ': [1],
'X X O   O': [1],
'X X  OO  ': [1],
'X X  O O ': [1],
'X X  O  O': [1],
'X X   OO ': [1],
'X X   O O': [1],
'X X    OO': [1],
'X OXO    ': [6],
'X OX O   ': [6],
'X OX  O  ': [4],
'X OX   O ': [6],
'X OX    O': [6],
'X OOX    ': [8],
'X OO X   ': [1, 4, 6, 7, 8],
'X OO  X  ': [8],
'X OO   X ': [4, 8],
'X OO    X': [4],
'X O XO   ': [8],
'X O X O  ': [8],
'X O X  O ': [8],
'X O X   O': [5],
'X O OX   ': [6],
'X O O X  ': [3],
'X O O  X ': [6],
'X O O   X': [6],
'X O  XO  ': [4],
'X O  X O ': [3, 4],
'X O  X  O': [3],
'X O  OX  ': [3],
'X O  O X ': [8],
'X O  O  X': [4],
'X O   XO ': [3],
'X O   X O': [3],
'X O   OX ': [4],
'X O   O X': [4],
'X O    XO': [5],
'X O    OX': [4],
'X  XOO   ': [6],
'X  XO O  ': [2],
'X  XO  O ': [6],
'X  XO   O': [6],
'X  X OO  ': [2, 8],
'X  X O O ': [6],
'X  X O  O': [6],
'X  X  OO ': [8],
'X  X  O O': [7],
'X  X   OO': [6],
'X  OXO   ': [8],
'X  OX O  ': [8],
'X  OX  O ': [8],
'X  OX   O': [1, 2],
'X  OOX   ': [2],
'X  OO X  ': [5],
'X  OO  X ': [5],
'X  OO   X': [5],
'X  O XO  ': [2, 8],
'X  O X O ': [2, 8],
'X  O X  O': [1, 2, 4, 6, 7],
'X  O OX  ': [4],
'X  O O X ': [4],
'X  O O  X': [4],
'X  O  XO ': [2, 4],
'X  O  X O': [2],
'X  O  OX ': [1, 4],
'X  O  O X': [4],
'X  O   XO': [1],
'X  O   OX': [4],
'X   XOO  ': [8],
'X   XO O ': [8],
'X   XO  O': [2],
'X   X OO ': [8],
'X   X O O': [7],
'X   X  OO': [6],
'X   OXO  ': [2],
'X   OX O ': [1],
'X   OX  O': [1, 2, 6, 7],
'X   OOX  ': [3],
'X   OO X ': [3],
'X   OO  X': [3],
'X   O XO ': [3],
'X   O X O': [3],
'X   O OX ': [2],
'X   O O X': [2],
'X   O  XO': [2, 3, 5, 6],
'X   O  OX': [1],
'X    XOO ': [8],
'X    XO O': [7],
'X    X OO': [6],
'X    OXO ': [3],
'X    OX O': [3],
'X    OOX ': [1, 4],
'X    OO X': [4],
'X    O XO': [2],
'X    O OX': [4],
'X     XOO': [3],
'X     OXO': [1],
'X     OOX': [4],
'OXXO     ': [6],
'OXX O    ': [8],
'OXX  O   ': [4],
'OXX   O  ': [3],
'OXX    O ': [6, 8],
'OXX     O': [4],
'OXOX     ': [4],
'OXO X    ': [7],
'OXO  X   ': [4],
'OXO   X  ': [7],
'OXO    X ': [4],
'OXO     X': [7],
'OX XO    ': [8],
'OX X O   ': [2, 4, 7, 8],
'OX X  O  ': [4],
'OX X   O ': [4, 5, 6, 8],
'OX X    O': [4],
'OX OX    ': [7],
'OX O X   ': [6],
'OX O  X  ': [4, 7],
'OX O   X ': [4],
'OX O    X': [6],
'OX  XO   ': [7],
'OX  X O  ': [7],
'OX  X  O ': [3, 5, 6, 8],
'OX  X   O': [7],
'OX  OX   ': [8],
'OX  O X  ': [8],
'OX  O  X ': [8],
'OX  O   X': [2, 3, 5, 6],
'OX   XO  ': [3],
'OX   X O ': [3, 4, 6, 8],
'OX   X  O': [4],
'OX   OX  ': [4, 7],
'OX   O X ': [4],
'OX   O  X': [7],
'OX    XO ': [2, 3, 4, 5, 8],
'OX    X O': [4],
'OX    OX ': [4],
'OX    O X': [3],
'OX     XO': [4],
'OX     OX': [2, 3, 4, 5, 6],
'OOXX     ': [4, 5],
'OOX X    ': [6],
'OOX  X   ': [8],
'OOX   X  ': [4],
'OOX    X ': [6, 8],
'OOX     X': [5],
'OO XX    ': [5],
'OO X X   ': [4],
'OO X  X  ': [2],
'OO X   X ': [2],
'OO X    X': [2],
'OO  XX   ': [3],
'OO  X X  ': [2],
'OO  X  X ': [2],
'OO  X   X': [2],
'OO   XX  ': [2],
'OO   X X ': [2],
'OO   X  X': [2],
'OO    XX ': [8],
'OO    X X': [7],
'OO     XX': [6],
'O XXO    ': [8],
'O XX O   ': [1, 4, 6, 7, 8],
'O XX  O  ': [5],
'O XX   O ': [4, 5],
'O XX    O': [4],
'O XOX    ': [6],
'O XO X   ': [8],
'O XO  X  ': [4],
'O XO   X ': [6],
'O XO    X': [5],
'O X XO   ': [6],
'O X X O  ': [3],
'O X X  O ': [6],
'O X X   O': [6],
'O X OX   ': [8],
'O X O X  ': [8],
'O X O  X ': [8],
'O X O   X': [5],
'O X  XO  ': [8],
'O X  X O ': [8],
'O X  X  O': [4],
'O X  OX  ': [4],
'O X  O X ': [4, 6],
'O X  O  X': [6],
'O X   XO ': [4],
'O X   X O': [4],
'O X   OX ': [3],
'O X   O X': [5],
'O X    XO': [4],
'O X    OX': [5],
'O OXX    ': [5],
'O OX X   ': [4],
'O OX  X  ': [1],
'O OX   X ': [1],
'O OX    X': [1],
'O O XX   ': [3],
'O O X X  ': [1],
'O O X  X ': [1],
'O O X   X': [1],
'O O  XX  ': [1],
'O O  X X ': [1],
'O O  X  X': [1],
'O O   XX ': [8],
'O O   X X': [7],
'O O    XX': [6],
'O  XXO   ': [1, 2, 7, 8],
'O  XX O  ': [5],
'O  XX  O ': [5],
'O  XX   O': [5],
'O  XOX   ': [8],
'O  XO X  ': [8],
'O  XO  X ': [8],
'O  XO   X': [1, 2, 6, 7],
'O  X XO  ': [4],
'O  X X O ': [4],
'O  X X  O': [4],
'O  X OX  ': [2, 8],
'O  X O X ': [1, 2, 4, 8],
'O  X O  X': [1, 2, 4, 6, 7],
'O  X  XO ': [4],
'O  X  X O': [4],
'O  X  OX ': [4],
'O  X  O X': [5],
'O  X   XO': [4],
'O  X   OX': [5],
'O  OXX   ': [6],
'O  OX X  ': [2],
'O  OX  X ': [1],
'O  OX   X': [6],
'O  O XX  ': [2, 8],
'O  O X X ': [6],
'O  O X  X': [2],
'O  O  XX ': [8],
'O  O  X X': [7],
'O  O   XX': [6],
'O   XXO  ': [3],
'O   XX O ': [3],
'O   XX  O': [3],
'O   XOX  ': [2],
'O   XO X ': [1],
'O   XO  X': [6, 7],
'O   X XO ': [2],
'O   X X O': [2],
'O   X OX ': [1],
'O   X O X': [3],
'O   X  XO': [1],
'O   X  OX': [2, 5],
'O   OXX  ': [8],
'O   OX X ': [8],
'O   OX  X': [2],
'O   O XX ': [8],
'O   O X X': [7],
'O   O  XX': [6],
'O    XXO ': [2, 4],
'O    XX O': [4],
'O    XOX ': [3],
'O    XO X': [2],
'O    X XO': [4],
'O    X OX': [2],
'O    OXX ': [8],
'O    OX X': [7],
'O    O XX': [6],
'O     XXO': [4],
'O     XOX': [2],
'O     OXX': [3],
' XXOO    ': [0],
' XXO O   ': [0],
' XXO  O  ': [0],
' XXO   O ': [0],
' XXO    O': [0],
' XX OO   ': [0],
' XX O O  ': [0],
' XX O  O ': [0],
' XX O   O': [0],
' XX  OO  ': [0],
' XX  O O ': [0],
' XX  O  O': [0],
' XX   OO ': [0],
' XX   O O': [0],
' XX    OO': [0],
' XOXO    ': [6],
' XOX O   ': [8],
' XOX  O  ': [4],
' XOX   O ': [4, 5, 6, 8],
' XOX    O': [5],
' XOOX    ': [7],
' XOO X   ': [0, 4, 6, 7],
' XOO  X  ': [7],
' XOO   X ': [4],
' XOO    X': [4, 7],
' XO XO   ': [7],
' XO X O  ': [7],
' XO X  O ': [3, 5, 6, 8],
' XO X   O': [7],
' XO OX   ': [6],
' XO O X  ': [0, 3, 5, 8],
' XO O  X ': [6],
' XO O   X': [6],
' XO  XO  ': [4],
' XO  X O ': [3, 4, 6, 8],
' XO  X  O': [4],
' XO  OX  ': [8],
' XO  O X ': [4],
' XO  O  X': [4, 7],
' XO   XO ': [0, 3, 4, 5, 8],
' XO   X O': [5],
' XO   OX ': [4],
' XO   O X': [4],
' XO    XO': [4],
' XO    OX': [0, 3, 4, 5, 6],
' X XOO   ': [0],
' X XO O  ': [2],
' X XO  O ': [0],
' X XO   O': [0],
' X X OO  ': [2, 4, 7, 8],
' X X O O ': [0],
' X X O  O': [2],
' X X  OO ': [8],
' X X  O O': [7],
' X X   OO': [6],
' X OXO   ': [7],
' X OX O  ': [7],
' X OX  O ': [0, 2],
' X OX   O': [7],
' X OOX   ': [2],
' X OO X  ': [5],
' X OO  X ': [5],
' X OO   X': [5],
' X O XO  ': [0],
' X O X O ': [2],
' X O X  O': [0, 4, 6, 7],
' X O OX  ': [4],
' X O O X ': [4],
' X O O  X': [4],
' X O  XO ': [2],
' X O  X O': [2, 4],
' X O  OX ': [4],
' X O  O X': [0],
' X O   XO': [4],
' X O   OX': [0, 2],
' X  XOO  ': [7],
' X  XO O ': [0, 2],
' X  XO  O': [7],
' X  X OO ': [8],
' X  X O O': [7],
' X  X  OO': [6],
' X  OXO  ': [2],
' X  OX O ': [2],
' X  OX  O': [0],
' X  OOX  ': [3],
' X  OO X ': [3],
' X  OO  X': [3],
' X  O XO ': [0],
' X  O X O': [0],
' X  O OX ': [2],
' X  O O X': [2],
' X  O  XO': [0],
' X  O  OX': [2],
' X   XOO ': [8],
' X   XO O': [7],
' X   X OO': [6],
' X   OXO ': [0, 2],
' X   OX O': [2],
' X   OOX ': [4],
' X   OO X': [0, 4],
' X   O XO': [4],
' X   O OX': [0],
' X    XOO': [0, 2],
' X    OXO': [4],
' X    OOX': [0, 2],
' OXXO    ': [7],
' OXX O   ': [6],
' OXX  O  ': [5],
' OXX   O ': [4],
' OXX    O': [4, 6],
' OXOX    ': [6],
' OXO X   ': [8],
' OXO  X  ': [4],
' OXO   X ': [6, 8],
' OXO    X': [5],
' OX XO   ': [6],
' OX X O  ': [5, 8],
' OX X  O ': [6],
' OX X   O': [6],
' OX OX   ': [8],
' OX O X  ': [7],
' OX O  X ': [8],
' OX O   X': [5],
' OX  XO  ': [8],
' OX  X O ': [8],
' OX  X  O': [4],
' OX  OX  ': [4],
' OX  O X ': [6],
' OX  O  X': [4, 6],
' OX   XO ': [4],
' OX   X O': [4],
' OX   OX ': [0, 3, 4, 5, 8],
' OX   O X': [5],
' OX    XO': [0, 3, 4, 5, 6],
' OX    OX': [5],
' OOXX    ': [5],
' OOX X   ': [4],
' OOX  X  ': [0],
' OOX   X ': [0],
' OOX    X': [0],
' OO XX   ': [3],
' OO X X  ': [0],
' OO X  X ': [0],
' OO X   X': [0],
' OO  XX  ': [0],
' OO  X X ': [0],
' OO  X  X': [0],
' OO   XX ': [8],
' OO   X X': [7],
' OO    XX': [6],
' O XXO   ': [0, 6],
' O XX O  ': [5],
' O XX  O ': [5],
' O XX   O': [5],
' O XOX   ': [7],
' O XO X  ': [0],
' O XO  X ': [6],
' O XO   X': [7],
' O X XO  ': [4],
' O X X O ': [4],
' O X X  O': [4],
' O X OX  ': [0],
' O X O X ': [6],
' O X O  X': [0, 6],
' O X  XO ': [0],
' O X  X O': [0],
' O X  OX ': [0, 2, 4, 5],
' O X  O X': [4, 5],
' O X   XO': [0, 2, 4, 5],
' O X   OX': [4],
' O OXX   ': [2, 8],
' O OX X  ': [2],
' O OX  X ': [6, 8],
' O OX   X': [0],
' O O XX  ': [2, 8],
' O O X X ': [8],
' O O X  X': [2],
' O O  XX ': [8],
' O O  X X': [7],
' O O   XX': [6],
' O  XXO  ': [3],
' O  XX O ': [3],
' O  XX  O': [3],
' O  XOX  ': [2],
' O  XO X ': [6, 8],
' O  XO  X': [0],
' O  X XO ': [2],
' O  X X O': [2],
' O  X OX ': [0, 2, 3, 5],
' O  X O X': [0],
' O  X  XO': [0, 2, 3, 5],
' O  X  OX': [0],
' O  OXX  ': [7],
' O  OX X ': [8],
' O  OX  X': [2],
' O  O XX ': [8],
' O  O X X': [7],
' O  O  XX': [6],
' O   XXO ': [4],
' O   XX O': [3, 4],
' O   XOX ': [0, 2, 3, 4],
' O   XO X': [2],
' O   X XO': [0, 2, 3, 4],
' O   X OX': [2],
' O   OXX ': [8],
' O   OX X': [7],
' O   O XX': [6],
' O    XXO': [0, 2],
' O    XOX': [4],
' O    OXX': [0, 2],
'  XXOO   ': [0],
'  XXO O  ': [0, 1, 7, 8],
'  XXO  O ': [1],
'  XXO   O': [0],
'  XX OO  ': [0, 1, 4, 7, 8],
'  XX O O ': [0, 6],
'  XX O  O': [0, 6],
'  XX  OO ': [8],
'  XX  O O': [7],
'  XX   OO': [6],
'  XOXO   ': [6],
'  XOX O  ': [0],
'  XOX  O ': [6],
'  XOX   O': [6],
'  XOOX   ': [8],
'  XOO X  ': [5],
'  XOO  X ': [5],
'  XOO   X': [5],
'  XO XO  ': [8],
'  XO X O ': [8],
'  XO X  O': [0, 6],
'  XO OX  ': [4],
'  XO O X ': [4],
'  XO O  X': [4],
'  XO  XO ': [4],
'  XO  X O': [4],
'  XO  OX ': [0],
'  XO  O X': [5],
'  XO   XO': [1, 4],
'  XO   OX': [5],
'  X XOO  ': [0, 1],
'  X XO O ': [6],
'  X XO  O': [6],
'  X X OO ': [8],
'  X X O O': [7],
'  X X  OO': [6],
'  X OXO  ': [8],
'  X OX O ': [8],
'  X OX  O': [0],
'  X OOX  ': [3],
'  X OO X ': [3],
'  X OO  X': [3],
'  X O XO ': [1],
'  X O X O': [0],
'  X O OX ': [0, 3, 5, 8],
'  X O O X': [5],
'  X O  XO': [0],
'  X O  OX': [5],
'  X  XOO ': [8],
'  X  XO O': [7],
'  X  X OO': [6],
'  X  OXO ': [4],
'  X  OX O': [4],
'  X  OOX ': [1],
'  X  OO X': [0],
'  X  O XO': [1, 4],
'  X  O OX': [0, 4],
'  X   XOO': [4],
'  X   OXO': [1],
'  X   OOX': [5],
'  OXXO   ': [8],
'  OXX O  ': [5],
'  OXX  O ': [5],
'  OXX   O': [5],
'  OXOX   ': [6],
'  OXO X  ': [0],
'  OXO  X ': [6],
'  OXO   X': [6],
'  OX XO  ': [4],
'  OX X O ': [4],
'  OX X  O': [4],
'  OX OX  ': [0],
'  OX O X ': [8],
'  OX O  X': [0, 6],
'  OX  XO ': [0],
'  OX  X O': [0],
'  OX  OX ': [4],
'  OX  O X': [4],
'  OX   XO': [5],
'  OX   OX': [0, 4],
'  OOXX   ': [0, 1, 6, 7],
'  OOX X  ': [7, 8],
'  OOX  X ': [1],
'  OOX   X': [0],
'  OO XX  ': [0, 1, 4, 7, 8],
'  OO X X ': [0, 1, 4, 6],
'  OO X  X': [0, 6],
'  OO  XX ': [8],
'  OO  X X': [7],
'  OO   XX': [6],
'  O XXO  ': [3],
'  O XX O ': [3],
'  O XX  O': [3],
'  O XOX  ': [8],
'  O XO X ': [1],
'  O XO  X': [0],
'  O X XO ': [0, 3],
'  O X X O': [5],
'  O X OX ': [1],
'  O X O X': [0],
'  O X  XO': [1],
'  O X  OX': [0],
'  O OXX  ': [0, 1, 7, 8],
'  O OX X ': [6],
'  O OX  X': [6],
'  O O XX ': [8],
'  O O X X': [7],
'  O O  XX': [6],
'  O  XXO ': [3],
'  O  XX O': [3],
'  O  XOX ': [4],
'  O  XO X': [4],
'  O  X XO': [4],
'  O  X OX': [4],
'  O  OXX ': [8],
'  O  OX X': [7],
'  O  O XX': [6],
'  O   XXO': [5],
'  O   XOX': [0],
'  O   OXX': [4],
'   XXOO  ': [1, 2, 7, 8],
'   XXO O ': [0, 6],
'   XXO  O': [2],
'   XX OO ': [5],
'   XX O O': [5],
'   XX  OO': [5],
'   XOXO  ': [2],
'   XOX O ': [1],
'   XOX  O': [0],
'   XOOX  ': [0],
'   XOO X ': [6],
'   XOO  X': [6],
'   XO XO ': [0],
'   XO X O': [0],
'   XO OX ': [2],
'   XO O X': [2],
'   XO  XO': [0],
'   XO  OX': [1],
'   X XOO ': [4],
'   X XO O': [4],
'   X X OO': [4],
'   X OXO ': [0],
'   X OX O': [0],
'   X OOX ': [1, 2, 4, 8],
'   X OO X': [0, 1, 2, 4, 7],
'   X O XO': [2],
'   X O OX': [0],
'   X  XOO': [0],
'   X  OXO': [4],
'   X  OOX': [4, 5],
'   OXXO  ': [0],
'   OXX O ': [2, 8],
'   OXX  O': [0, 1, 6, 7],
'   OXOX  ': [2],
'   OXO X ': [1],
'   OXO  X': [0],
'   OX XO ': [2],
'   OX X O': [2],
'   OX OX ': [1],
'   OX O X': [0],
'   OX  XO': [1],
'   OX  OX': [0],
'   OOXX  ': [8],
'   OOX X ': [8],
'   OOX  X': [2],
'   OO XX ': [8],
'   OO X X': [7],
'   OO  XX': [6],
'   O XXO ': [2],
'   O XX O': [0, 1, 2, 4, 7],
'   O XOX ': [0],
'   O XO X': [2],
'   O X XO': [0, 1, 4, 6],
'   O X OX': [2],
'   O OXX ': [8],
'   O OX X': [7],
'   O O XX': [6],
'   O  XXO': [4],
'   O  XOX': [2, 4],
'   O  OXX': [0],
'    XXOO ': [3],
'    XXO O': [3],
'    XX OO': [3],
'    XOXO ': [2],
'    XOX O': [2],
'    XOOX ': [1],
'    XOO X': [0],
'    XO XO': [1],
'    XO OX': [0],
'    X XOO': [2],
'    X OXO': [1],
'    X OOX': [0],
'    OXXO ': [1],
'    OXX O': [0],
'    OXOX ': [2],
'    OXO X': [2],
'    OX XO': [0],
'    OX OX': [2],
'    OOXX ': [8],
'    OOX X': [7],
'    OO XX': [6],
'    O XXO': [0],
'    O XOX': [1],
'    O OXX': [2],
'     XXOO': [3, 4],
'     XOXO': [4],
'     XOOX': [2],
'     OXXO': [2],
'     OXOX': [0, 4],
'     OOXX': [4]}

book5 = {
'XXOXO    ': [6],
'XXOX O   ': [8],
'XXOX  O  ': [4],
'XXOX   O ': [6],
'XXOX    O': [5],
'XXOOX    ': [5, 6, 7, 8],
'XXOO X   ': [4, 7, 8],
'XXOO  X  ': [5],
'XXOO   X ': [4],
'XXOO    X': [4],
'XXO XO   ': [8],
'XXO X O  ': [3, 5, 7, 8],
'XXO X  O ': [8],
'XXO X   O': [5],
'XXO OX   ': [6],
'XXO O X  ': [3],
'XXO O  X ': [6],
'XXO O   X': [6],
'XXO  XO  ': [4],
'XXO  X O ': [6],
'XXO  X  O': [6],
'XXO  OX  ': [8],
'XXO  O X ': [8],
'XXO  O  X': [4],
'XXO   XO ': [3],
'XXO   X O': [5],
'XXO   OX ': [4],
'XXO   O X': [4],
'XXO    XO': [5],
'XXO    OX': [4],
'XX XOO   ': [2, 6, 7, 8],
'XX XO O  ': [2],
'XX XO  O ': [2, 5, 6, 8],
'XX XO   O': [2, 5, 6, 7],
'XX X OO  ': [2],
'XX X O O ': [2, 4, 6, 8],
'XX X O  O': [2],
'XX X  OO ': [8],
'XX X  O O': [7],
'XX X   OO': [6],
'XX OXO   ': [2, 6, 7, 8],
'XX OX O  ': [2, 5, 7, 8],
'XX OX  O ': [2, 5, 6, 8],
'XX OX   O': [2, 5, 6, 7],
'XX OOX   ': [2],
'XX OO X  ': [5],
'XX OO  X ': [5],
'XX OO   X': [5],
'XX O XO  ': [2],
'XX O X O ': [2],
'XX O X  O': [2],
'XX O OX  ': [4],
'XX O O X ': [4],
'XX O O  X': [4],
'XX O  XO ': [2],
'XX O  X O': [2],
'XX O  OX ': [2, 4, 5, 8],
'XX O  O X': [2, 4, 5, 7],
'XX O   XO': [2, 4, 5, 6],
'XX O   OX': [2, 4, 5, 6],
'XX  XOO  ': [2, 3, 7, 8],
'XX  XO O ': [2, 3, 6, 8],
'XX  XO  O': [2],
'XX  X OO ': [8],
'XX  X O O': [7],
'XX  X  OO': [6],
'XX  OXO  ': [2],
'XX  OX O ': [2],
'XX  OX  O': [2],
'XX  OOX  ': [3],
'XX  OO X ': [3],
'XX  OO  X': [3],
'XX  O XO ': [2, 3, 5, 8],
'XX  O X O': [2, 3, 5, 7],
'XX  O OX ': [2],
'XX  O O X': [2],
'XX  O  XO': [2],
'XX  O  OX': [2],
'XX   XOO ': [8],
'XX   XO O': [7],
'XX   X OO': [6],
'XX   OXO ': [2, 3, 4, 8],
'XX   OX O': [2],
'XX   OOX ': [2, 3, 4, 8],
'XX   OO X': [2, 3, 4, 7],
'XX   O XO': [2],
'XX   O OX': [2, 3, 4, 6],
'XX    XOO': [2, 3, 4, 5],
'XX    OXO': [2, 3, 4, 5],
'XX    OOX': [2, 3, 4, 5],
'XOXXO    ': [7],
'XOXX O   ': [6],
'XOXX  O  ': [7],
'XOXX   O ': [4],
'XOXX    O': [6],
'XOXOX    ': [5, 6, 7, 8],
'XOXO X   ': [8],
'XOXO  X  ': [4],
'XOXO   X ': [4, 8],
'XOXO    X': [4, 5, 6, 7],
'XOX XO   ': [3, 6, 7, 8],
'XOX X O  ': [8],
'XOX X  O ': [3, 5, 6, 8],
'XOX X   O': [6],
'XOX OX   ': [7],
'XOX O X  ': [7],
'XOX O  X ': [3, 5, 6, 8],
'XOX O   X': [7],
'XOX  XO  ': [8],
'XOX  X O ': [4],
'XOX  X  O': [7],
'XOX  OX  ': [3, 4, 7, 8],
'XOX  O X ': [4, 6],
'XOX  O  X': [4],
'XOX   XO ': [4],
'XOX   X O': [3, 4, 5, 7],
'XOX   OX ': [4, 5, 8],
'XOX   O X': [3, 4, 5, 7],
'XOX    XO': [3, 4, 6],
'XOX    OX': [4],
'XOOXX    ': [5, 6, 7, 8],
'XOOX X   ': [4, 6, 7, 8],
'XOOX   X ': [6],
'XOOX    X': [4, 5, 6, 7],
'XOO XX   ': [3, 6, 7, 8],
'XOO X X  ': [3, 5, 7, 8],
'XOO X  X ': [8],
'XOO  XX  ': [3],
'XOO  X X ': [3, 4, 6, 8],
'XOO  X  X': [4],
'XOO   XX ': [3, 4, 5, 8],
'XOO   X X': [3, 4, 5, 7],
'XOO    XX': [3, 4, 5, 6],
'XO XXO   ': [2, 6, 7, 8],
'XO XX O  ': [2, 5, 7, 8],
'XO XX  O ': [2, 5, 6, 8],
'XO XX   O': [2, 5, 6, 7],
'XO XOX   ': [7],
'XO XO  X ': [6],
'XO XO   X': [7],
'XO X XO  ': [4],
'XO X X O ': [4],
'XO X X  O': [2, 4, 6, 7],
'XO X O X ': [6],
'XO X O  X': [2, 4, 6, 7],
'XO X  OX ': [4, 5, 8],
'XO X  O X': [4],
'XO X   XO': [6],
'XO X   OX': [4],
'XO OXX   ': [8],
'XO OX X  ': [2, 5, 7, 8],
'XO OX  X ': [8],
'XO O XX  ': [4, 8],
'XO O X X ': [8],
'XO O X  X': [2, 4, 6, 7],
'XO O  XX ': [8],
'XO O  X X': [2, 4, 5, 7],
'XO O   XX': [2, 4, 5, 6],
'XO  XXO  ': [2, 3, 7, 8],
'XO  XX O ': [2, 3, 6, 8],
'XO  XX  O': [3],
'XO  XOX  ': [2, 3, 7, 8],
'XO  XO X ': [8],
'XO  X XO ': [2, 3, 5, 8],
'XO  X X O': [2, 3, 5, 7],
'XO  X OX ': [8],
'XO  X  XO': [2, 3, 5, 6],
'XO  OXX  ': [7],
'XO  OX X ': [6, 8],
'XO  OX  X': [7],
'XO  O XX ': [2, 3, 5, 8],
'XO  O X X': [7],
'XO  O  XX': [6],
'XO   XXO ': [4],
'XO   XX O': [3],
'XO   XOX ': [4, 8],
'XO   XO X': [2, 3, 4, 7],
'XO   X XO': [3, 4, 6],
'XO   X OX': [4],
'XO   OXX ': [2, 3, 4, 8],
'XO   OX X': [2, 3, 4, 7],
'XO   O XX': [2, 3, 4, 6],
'XO    XXO': [3],
'XO    XOX': [4],
'XO    OXX': [4],
'X XXOO   ': [1, 6, 7, 8],
'X XXO O  ': [1],
'X XXO  O ': [1],
'X XXO   O': [1, 5, 6, 7],
'X XX OO  ': [1],
'X XX O O ': [1, 4, 6, 8],
'X XX O  O': [1, 4, 6, 7],
'X XX  OO ': [8],
'X XX  O O': [7],
'X XX   OO': [6],
'X XOXO   ': [1, 6, 7, 8],
'X XOX O  ': [1, 5, 7, 8],
'X XOX  O ': [1, 5, 6, 8],
'X XOX   O': [1, 5, 6, 7],
'X XOOX   ': [1, 6, 7, 8],
'X XOO X  ': [5],
'X XOO  X ': [5],
'X XOO   X': [5],
'X XO XO  ': [1, 4, 7, 8],
'X XO X O ': [1, 4, 6, 8],
'X XO X  O': [1],
'X XO OX  ': [4],
'X XO O X ': [4],
'X XO O  X': [4],
'X XO  XO ': [1, 4, 5, 8],
'X XO  X O': [1, 4, 5, 7],
'X XO  OX ': [1],
'X XO  O X': [1, 4, 5, 7],
'X XO   XO': [1],
'X XO   OX': [1, 4, 5, 6],
'X X XOO  ': [1, 3, 7, 8],
'X X XO O ': [1, 3, 6, 8],
'X X XO  O': [1, 3, 6, 7],
'X X X OO ': [8],
'X X X O O': [7],
'X X X  OO': [6],
'X X OXO  ': [1, 3, 7, 8],
'X X OX O ': [1],
'X X OX  O': [1],
'X X OOX  ': [3],
'X X OO X ': [3],
'X X OO  X': [3],
'X X O XO ': [1],
'X X O X O': [1, 3, 5, 7],
'X X O OX ': [1],
'X X O O X': [1, 3, 5, 7],
'X X O  XO': [1],
'X X O  OX': [1],
'X X  XOO ': [8],
'X X  XO O': [7],
'X X  X OO': [6],
'X X  OXO ': [1, 3, 4, 8],
'X X  OX O': [1, 3, 4, 7],
'X X  OOX ': [1],
'X X  OO X': [1, 3, 4, 7],
'X X  O XO': [1],
'X X  O OX': [1, 3, 4, 6],
'X X   XOO': [1, 3, 4, 5],
'X X   OXO': [1],
'X X   OOX': [1, 3, 4, 5],
'X OXXO   ': [8],
'X OXX O  ': [1, 5, 7, 8],
'X OXX  O ': [1, 5, 6, 8],
'X OXX   O': [5],
'X OXOX   ': [6],
'X OXO  X ': [6],
'X OXO   X': [6],
'X OX XO  ': [4],
'X OX X O ': [1, 4, 6, 8],
'X OX X  O': [1, 4, 6, 7],
'X OX O X ': [8],
'X OX O  X': [1, 4, 6, 7],
'X OX  OX ': [4],
'X OX  O X': [4],
'X OX   XO': [5],
'X OX   OX': [1, 4, 5, 6],
'X OOXX   ': [8],
'X OOX X  ': [8],
'X OOX  X ': [1, 5, 6, 8],
'X OO XX  ': [4, 7, 8],
'X OO X X ': [4, 8],
'X OO X  X': [4],
'X OO  XX ': [8],
'X OO  X X': [1, 4, 5, 7],
'X OO   XX': [1, 4, 5, 6],
'X O XXO  ': [1, 3, 7, 8],
'X O XX O ': [1, 3, 6, 8],
'X O XX  O': [3],
'X O XOX  ': [8],
'X O XO X ': [8],
'X O X XO ': [1, 3, 5, 8],
'X O X X O': [5],
'X O X OX ': [1, 3, 5, 8],
'X O X  XO': [5],
'X O OXX  ': [3],
'X O OX X ': [6],
'X O OX  X': [6],
'X O O XX ': [1, 3, 5, 8],
'X O O X X': [1, 3, 5, 7],
'X O O  XX': [6],
'X O  XXO ': [3],
'X O  XX O': [3],
'X O  XOX ': [4],
'X O  XO X': [4],
'X O  X XO': [3, 4],
'X O  X OX': [4],
'X O  OXX ': [8],
'X O  OX X': [1, 3, 4, 7],
'X O  O XX': [1, 3, 4, 6],
'X O   XXO': [5],
'X O   XOX': [1, 3, 4, 5],
'X O   OXX': [4],
'X  XXOO  ': [8],
'X  XXO O ': [1, 2, 6, 8],
'X  XXO  O': [2],
'X  XX OO ': [8],
'X  XX O O': [7],
'X  XX  OO': [6],
'X  XOXO  ': [2],
'X  XOX O ': [1],
'X  XOX  O': [6],
'X  XOO X ': [6],
'X  XOO  X': [6],
'X  XO OX ': [2],
'X  XO O X': [2],
'X  XO  XO': [6],
'X  XO  OX': [1],
'X  X XOO ': [8],
'X  X XO O': [7],
'X  X X OO': [6],
'X  X OOX ': [2],
'X  X OO X': [4],
'X  X O XO': [2],
'X  X O OX': [1, 2, 4, 6],
'X  X  OXO': [2],
'X  X  OOX': [4],
'X  OXXO  ': [8],
'X  OXX O ': [8],
'X  OXX  O': [1, 2, 6, 7],
'X  OXOX  ': [1, 2, 7, 8],
'X  OXO X ': [1, 2, 6, 8],
'X  OX XO ': [1, 2, 5, 8],
'X  OX X O': [2],
'X  OX OX ': [1, 2, 5, 8],
'X  OX  XO': [1],
'X  OOXX  ': [1, 2, 7, 8],
'X  OOX X ': [2, 8],
'X  OOX  X': [2],
'X  OO XX ': [5],
'X  OO X X': [5],
'X  OO  XX': [5],
'X  O XXO ': [2, 4],
'X  O XX O': [1, 2, 4],
'X  O XOX ': [1, 2, 4, 8],
'X  O XO X': [1, 2, 4, 7],
'X  O X XO': [1, 2, 4],
'X  O X OX': [1, 2, 4, 6],
'X  O OXX ': [4],
'X  O OX X': [4],
'X  O O XX': [4],
'X  O  XXO': [5],
'X  O  XOX': [4],
'X  O  OXX': [4],
'X   XXOO ': [8],
'X   XXO O': [7],
'X   XX OO': [6],
'X   XOXO ': [1, 2, 3, 8],
'X   XOX O': [2],
'X   XOOX ': [1, 2, 3, 8],
'X   XO XO': [2],
'X   X XOO': [1, 2, 3, 5],
'X   X OXO': [1],
'X   OXXO ': [1],
'X   OXX O': [3],
'X   OXOX ': [2],
'X   OXO X': [2],
'X   OX XO': [1, 2, 3, 6],
'X   OX OX': [1],
'X   OOXX ': [3],
'X   OOX X': [3],
'X   OO XX': [3],
'X   O XXO': [3],
'X   O XOX': [1],
'X   O OXX': [2],
'X    XXOO': [3],
'X    XOXO': [1, 4],
'X    XOOX': [1, 2, 3, 4],
'X    OXXO': [2],
'X    OXOX': [1, 2, 3, 4],
'X    OOXX': [4],
'OXXXO    ': [8],
'OXXX O   ': [4, 6, 7],
'OXXX  O  ': [8],
'OXXX   O ': [8],
'OXXX    O': [4],
'OXXOX    ': [6],
'OXXO X   ': [6],
'OXXO  X  ': [4],
'OXXO   X ': [6],
'OXXO    X': [6],
'OXX XO   ': [3, 6, 7, 8],
'OXX X O  ': [3],
'OXX X  O ': [6],
'OXX X   O': [3, 5, 6, 7],
'OXX OX   ': [8],
'OXX O X  ': [8],
'OXX O  X ': [8],
'OXX O   X': [5],
'OXX  XO  ': [3],
'OXX  X O ': [8],
'OXX  X  O': [4],
'OXX  OX  ': [4],
'OXX  O X ': [4],
'OXX  O  X': [3],
'OXX   XO ': [4],
'OXX   X O': [4],
'OXX   OX ': [3],
'OXX   O X': [3],
'OXX    XO': [4],
'OXX    OX': [5],
'OXOXX    ': [5, 6, 7, 8],
'OXOX X   ': [4],
'OXOX  X  ': [8],
'OXOX   X ': [4],
'OXOX    X': [4, 7],
'OXO XX   ': [3, 6, 7, 8],
'OXO X X  ': [7],
'OXO X   X': [7],
'OXO  XX  ': [4, 7],
'OXO  X X ': [4],
'OXO  X  X': [6],
'OXO   XX ': [3, 4, 5, 8],
'OXO   X X': [7],
'OXO    XX': [3, 4, 5, 6],
'OX XXO   ': [7],
'OX XX O  ': [2, 5, 7, 8],
'OX XX  O ': [5],
'OX XX   O': [2, 5, 6, 7],
'OX XOX   ': [8],
'OX XO X  ': [8],
'OX XO  X ': [8],
'OX XO   X': [2, 5, 6, 7],
'OX X XO  ': [4],
'OX X X O ': [4],
'OX X X  O': [4],
'OX X OX  ': [8],
'OX X O X ': [4],
'OX X O  X': [4, 6, 7],
'OX X  XO ': [2, 4, 5],
'OX X  X O': [4],
'OX X  OX ': [4],
'OX X  O X': [4, 5],
'OX X   XO': [4],
'OX X   OX': [2, 4, 5],
'OX OXX   ': [6],
'OX OX X  ': [2, 5, 7, 8],
'OX OX   X': [6],
'OX O XX  ': [2, 4, 7, 8],
'OX O X X ': [6],
'OX O X  X': [6],
'OX O  XX ': [2, 4, 5, 8],
'OX O  X X': [7],
'OX O   XX': [6],
'OX  XXO  ': [3],
'OX  XX O ': [3],
'OX  XX  O': [2, 3, 6, 7],
'OX  XOX  ': [2, 3, 7, 8],
'OX  XO  X': [7],
'OX  X XO ': [2],
'OX  X X O': [2, 3, 5, 7],
'OX  X O X': [3],
'OX  X  OX': [2, 3, 5, 6],
'OX  OXX  ': [8],
'OX  OX X ': [8],
'OX  OX  X': [2],
'OX  O XX ': [8],
'OX  O X X': [7],
'OX  O  XX': [6],
'OX   XXO ': [2, 4],
'OX   XX O': [4],
'OX   XOX ': [3],
'OX   XO X': [3],
'OX   X XO': [4],
'OX   X OX': [2],
'OX   OXX ': [2, 3, 4, 8],
'OX   OX X': [7],
'OX   O XX': [2, 3, 4, 6],
'OX    XXO': [4],
'OX    XOX': [2, 4, 5],
'OX    OXX': [3],
'OOXXX    ': [5, 6, 7, 8],
'OOXX X   ': [4, 6, 7, 8],
'OOXX  X  ': [4],
'OOXX   X ': [4, 5, 6, 8],
'OOXX    X': [5],
'OOX XX   ': [3, 6, 7, 8],
'OOX X  X ': [6],
'OOX X   X': [3, 5, 6, 7],
'OOX  XX  ': [3, 4, 7, 8],
'OOX  X X ': [8],
'OOX   XX ': [3, 4, 5, 8],
'OOX   X X': [3, 4, 5, 7],
'OOX    XX': [3, 4, 5, 6],
'OO XX X  ': [2],
'OO XX  X ': [2],
'OO XX   X': [2],
'OO X XX  ': [2],
'OO X X X ': [2],
'OO X X  X': [2],
'OO X  XX ': [2],
'OO X  X X': [2],
'OO X   XX': [2],
'OO  XXX  ': [2],
'OO  XX X ': [2],
'OO  XX  X': [2],
'OO  X XX ': [2],
'OO  X X X': [2],
'OO  X  XX': [2],
'OO   XXX ': [2],
'OO   XX X': [2],
'OO   X XX': [2],
'O XXXO   ': [6],
'O XXX O  ': [5],
'O XXX  O ': [1, 5, 6, 8],
'O XXX   O': [1, 5, 6, 7],
'O XXOX   ': [8],
'O XXO X  ': [8],
'O XXO  X ': [8],
'O XXO   X': [5],
'O XX XO  ': [1, 4, 7, 8],
'O XX X O ': [1, 4, 6, 8],
'O XX X  O': [4],
'O XX OX  ': [4],
'O XX O X ': [4, 6],
'O XX O  X': [4, 6, 7],
'O XX  XO ': [4],
'O XX  X O': [4],
'O XX  OX ': [4, 5],
'O XX  O X': [5],
'O XX   XO': [4],
'O XX   OX': [5],
'O XOXX   ': [6],
'O XOX  X ': [6],
'O XOX   X': [6],
'O XO XX  ': [1, 4, 7, 8],
'O XO X X ': [6],
'O XO  XX ': [1, 4, 5, 8],
'O XO  X X': [1, 4, 5, 7],
'O XO   XX': [6],
'O X XXO  ': [3],
'O X XX O ': [1, 3, 6, 8],
'O X XX  O': [1, 3, 6, 7],
'O X XO X ': [1, 3, 6, 8],
'O X XO  X': [6],
'O X X OX ': [3],
'O X X O X': [3],
'O X X  XO': [1, 3, 5, 6],
'O X X  OX': [1, 3, 5, 6],
'O X OXX  ': [8],
'O X OX X ': [8],
'O X O XX ': [8],
'O X O X X': [1, 3, 5, 7],
'O X O  XX': [1, 3, 5, 6],
'O X  XXO ': [1, 3, 4, 8],
'O X  XX O': [4],
'O X  XOX ': [3],
'O X  X XO': [4],
'O X  OXX ': [1, 3, 4, 8],
'O X  OX X': [1, 3, 4, 7],
'O X  O XX': [6],
'O X   XXO': [4],
'O X   XOX': [1, 3, 4, 5],
'O X   OXX': [3],
'O OXX X  ': [1],
'O OXX  X ': [1],
'O OXX   X': [1],
'O OX XX  ': [1],
'O OX X X ': [1],
'O OX X  X': [1],
'O OX  XX ': [1],
'O OX  X X': [1],
'O OX   XX': [1],
'O O XXX  ': [1],
'O O XX X ': [1],
'O O XX  X': [1],
'O O X XX ': [1],
'O O X X X': [1],
'O O X  XX': [1],
'O O  XXX ': [1],
'O O  XX X': [1],
'O O  X XX': [1],
'O  XXOX  ': [2],
'O  XXO X ': [1],
'O  XXO  X': [1, 2, 6, 7],
'O  XX XO ': [1, 2, 5, 8],
'O  XX X O': [1, 2, 5, 7],
'O  XX OX ': [1, 2, 5, 8],
'O  XX O X': [5],
'O  XX  XO': [1, 2, 5, 6],
'O  XX  OX': [5],
'O  XOXX  ': [8],
'O  XOX X ': [8],
'O  XOX  X': [2],
'O  XO XX ': [8],
'O  XO X X': [7],
'O  XO  XX': [6],
'O  X XXO ': [4],
'O  X XX O': [4],
'O  X XOX ': [4],
'O  X XO X': [1, 2, 4, 7],
'O  X X XO': [4],
'O  X X OX': [1, 2, 4, 6],
'O  X OXX ': [8],
'O  X OX X': [7],
'O  X O XX': [6],
'O  X  XXO': [4],
'O  X  XOX': [1],
'O  X  OXX': [2],
'O  OXXX  ': [2],
'O  OXX X ': [6],
'O  OXX  X': [6],
'O  OX XX ': [1, 2, 5, 8],
'O  OX X X': [1, 2, 5, 7],
'O  OX  XX': [6],
'O  O XXX ': [8],
'O  O XX X': [1, 2, 4, 7],
'O  O X XX': [6],
'O   XXXO ': [1, 2, 3, 8],
'O   XXX O': [1, 2, 3, 7],
'O   XXOX ': [3],
'O   XXO X': [3],
'O   XX XO': [1, 2, 3, 6],
'O   XX OX': [1, 2, 3, 6],
'O   XOXX ': [1, 2, 3, 8],
'O   XOX X': [1, 2, 3, 7],
'O   XO XX': [1, 2, 3, 6],
'O   X XXO': [1, 2, 3, 5],
'O   X XOX': [2],
'O   X OXX': [3],
'O   OXXX ': [8],
'O   OXX X': [1, 2, 3, 7],
'O   OX XX': [1, 2, 3, 6],
'O    XXXO': [4],
'O    XXOX': [2],
'O    XOXX': [3],
' XXXOO   ': [0],
' XXXO O  ': [0],
' XXXO  O ': [0],
' XXXO   O': [0],
' XXX OO  ': [0],
' XXX O O ': [0],
' XXX O  O': [0],
' XXX  OO ': [8],
' XXX  O O': [7],
' XXX   OO': [6],
' XXOXO   ': [0, 6, 7, 8],
' XXOX O  ': [0],
' XXOX  O ': [0, 5, 6, 8],
' XXOX   O': [0, 5, 6, 7],
' XXOOX   ': [0, 6, 7, 8],
' XXOO X  ': [5],
' XXOO  X ': [5],
' XXOO   X': [5],
' XXO XO  ': [0],
' XXO X O ': [0, 4, 6, 8],
' XXO X  O': [0],
' XXO OX  ': [4],
' XXO O X ': [4],
' XXO O  X': [4],
' XXO  XO ': [0, 4, 5, 8],
' XXO  X O': [0, 4, 5, 7],
' XXO  OX ': [0],
' XXO  O X': [0],
' XXO   XO': [0, 4, 5, 6],
' XXO   OX': [0, 4, 5, 6],
' XX XOO  ': [0, 3, 7, 8],
' XX XO O ': [0, 3, 6, 8],
' XX XO  O': [0, 3, 6, 7],
' XX X OO ': [8],
' XX X O O': [7],
' XX X  OO': [6],
' XX OXO  ': [0, 3, 7, 8],
' XX OX O ': [0, 3, 6, 8],
' XX OX  O': [0],
' XX OOX  ': [3],
' XX OO X ': [3],
' XX OO  X': [3],
' XX O XO ': [0],
' XX O X O': [0],
' XX O OX ': [0],
' XX O O X': [0, 3, 5, 7],
' XX O  XO': [0],
' XX O  OX': [0, 3, 5, 6],
' XX  XOO ': [8],
' XX  XO O': [7],
' XX  X OO': [6],
' XX  OXO ': [0, 3, 4, 8],
' XX  OX O': [0, 3, 4, 7],
' XX  OOX ': [0, 3, 4, 8],
' XX  OO X': [0],
' XX  O XO': [0, 3, 4, 6],
' XX  O OX': [0],
' XX   XOO': [0, 3, 4, 5],
' XX   OXO': [0, 3, 4, 5],
' XX   OOX': [0, 3, 4, 5],
' XOXXO   ': [8],
' XOXX O  ': [0, 5, 7, 8],
' XOXX  O ': [5],
' XOXX   O': [5],
' XOXOX   ': [6],
' XOXO X  ': [0],
' XOXO  X ': [6],
' XOXO   X': [6],
' XOX XO  ': [4],
' XOX X O ': [4],
' XOX X  O': [4],
' XOX OX  ': [8],
' XOX O X ': [8],
' XOX O  X': [0, 4, 6, 7],
' XOX  XO ': [0],
' XOX  X O': [5],
' XOX  OX ': [4],
' XOX  O X': [4],
' XOX   XO': [5],
' XOX   OX': [0, 4],
' XOOXX   ': [7],
' XOOX X  ': [7],
' XOOX   X': [0, 5, 6, 7],
' XOO XX  ': [4, 7, 8],
' XOO X X ': [4],
' XOO X  X': [6],
' XOO  XX ': [0, 4, 5, 8],
' XOO  X X': [7],
' XOO   XX': [0, 4, 5, 6],
' XO XXO  ': [0, 3, 7, 8],
' XO XX O ': [3],
' XO XX  O': [0, 3, 6, 7],
' XO XOX  ': [8],
' XO XO  X': [0, 3, 6, 7],
' XO X XO ': [0, 3, 5, 8],
' XO X X O': [5],
' XO X O X': [0, 3, 5, 7],
' XO X  OX': [0],
' XO OXX  ': [0, 3, 7, 8],
' XO OX X ': [6],
' XO OX  X': [6],
' XO O XX ': [8],
' XO O X X': [7],
' XO O  XX': [6],
' XO  XXO ': [0, 3, 4],
' XO  XX O': [3, 4],
' XO  XOX ': [4],
' XO  XO X': [4],
' XO  X XO': [4],
' XO  X OX': [0, 3, 4],
' XO  OXX ': [8],
' XO  OX X': [7],
' XO  O XX': [0, 3, 4, 6],
' XO   XXO': [5],
' XO   XOX': [0, 3, 4],
' XO   OXX': [4],
' X XXOO  ': [7],
' X XXO O ': [8],
' X XXO  O': [2],
' X XX OO ': [8],
' X XX O O': [7],
' X XX  OO': [6],
' X XOXO  ': [2],
' X XOX O ': [6, 8],
' X XOX  O': [0],
' X XOOX  ': [0],
' X XOO X ': [2, 8],
' X XOO  X': [0, 6],
' X XO XO ': [0],
' X XO X O': [0],
' X XO OX ': [2],
' X XO O X': [2],
' X XO  XO': [0],
' X XO  OX': [0, 2],
' X X XOO ': [8],
' X X XO O': [7],
' X X X OO': [6],
' X X OXO ': [0],
' X X OX O': [2],
' X X OOX ': [4],
' X X OO X': [0, 4],
' X X O XO': [2],
' X X O OX': [0],
' X X  XOO': [0],
' X X  OXO': [4],
' X X  OOX': [0, 2, 4, 5],
' X OXXO  ': [0],
' X OXX O ': [6],
' X OXX  O': [7],
' X OXOX  ': [0, 2, 7, 8],
' X OXO  X': [0, 2, 6, 7],
' X OX XO ': [2],
' X OX X O': [0, 2, 5, 7],
' X OX O X': [0],
' X OX  OX': [0],
' X OOXX  ': [2, 8],
' X OOX X ': [0, 6],
' X OOX  X': [2],
' X OO XX ': [5],
' X OO X X': [5],
' X OO  XX': [5],
' X O XXO ': [2],
' X O XX O': [2, 4],
' X O XOX ': [0],
' X O XO X': [0],
' X O X XO': [4],
' X O X OX': [2],
' X O OXX ': [4],
' X O OX X': [4],
' X O O XX': [4],
' X O  XXO': [4],
' X O  XOX': [2, 4],
' X O  OXX': [0],
' X  XXOO ': [8],
' X  XXO O': [7],
' X  XX OO': [6],
' X  XOXO ': [2],
' X  XOX O': [2],
' X  XOO X': [0, 2, 3, 7],
' X  XO OX': [0],
' X  X XOO': [2],
' X  X OOX': [0],
' X  OXXO ': [0, 2],
' X  OXX O': [0],
' X  OXOX ': [2],
' X  OXO X': [2],
' X  OX XO': [0],
' X  OX OX': [2],
' X  OOXX ': [3],
' X  OOX X': [3],
' X  OO XX': [3],
' X  O XXO': [0],
' X  O XOX': [0, 2, 3, 5],
' X  O OXX': [2],
' X   XXOO': [0, 2, 3, 4],
' X   XOXO': [4],
' X   XOOX': [2],
' X   OXXO': [2],
' X   OXOX': [0, 4],
' X   OOXX': [4],
' OXXXO   ': [6],
' OXXX O  ': [5],
' OXXX  O ': [0, 5, 6, 8],
' OXXX   O': [0, 5, 6, 7],
' OXXOX   ': [7],
' OXXO X  ': [7],
' OXXO  X ': [6, 8],
' OXXO   X': [7],
' OXX XO  ': [0, 4, 7, 8],
' OXX X O ': [4],
' OXX X  O': [4],
' OXX OX  ': [0, 4, 7, 8],
' OXX O X ': [6],
' OXX O  X': [4, 6],
' OXX  XO ': [4],
' OXX  X O': [0, 4, 5, 7],
' OXX  OX ': [4, 5, 8],
' OXX  O X': [5],
' OXX   XO': [4, 6],
' OXX   OX': [4],
' OXOXX   ': [0, 6, 7, 8],
' OXOX  X ': [6],
' OXOX   X': [0, 5, 6, 7],
' OXO XX  ': [0, 4, 7, 8],
' OXO X X ': [8],
' OXO  XX ': [0, 4, 5, 8],
' OXO  X X': [0, 4, 5, 7],
' OXO   XX': [0, 4, 5, 6],
' OX XXO  ': [0, 3, 7, 8],
' OX XX O ': [0, 3, 6, 8],
' OX XX  O': [0, 3, 6, 7],
' OX XO X ': [6],
' OX XO  X': [0, 3, 6, 7],
' OX X OX ': [0, 3, 5, 8],
' OX X O X': [0, 3, 5, 7],
' OX X  XO': [6],
' OX X  OX': [0, 3, 5, 6],
' OX OXX  ': [7],
' OX OX X ': [8],
' OX O XX ': [8],
' OX O X X': [7],
' OX O  XX': [0, 3, 5, 6],
' OX  XXO ': [4],
' OX  XX O': [4],
' OX  XOX ': [8],
' OX  X XO': [3, 4, 6],
' OX  OXX ': [0, 3, 4, 8],
' OX  OX X': [0, 3, 4, 7],
' OX  O XX': [6],
' OX   XXO': [4],
' OX   XOX': [4],
' OX   OXX': [5],
' OOXX X  ': [0],
' OOXX  X ': [0],
' OOXX   X': [0],
' OOX XX  ': [0],
' OOX X X ': [0],
' OOX X  X': [0],
' OOX  XX ': [0],
' OOX  X X': [0],
' OOX   XX': [0],
' OO XXX  ': [0],
' OO XX X ': [0],
' OO XX  X': [0],
' OO X XX ': [0],
' OO X X X': [0],
' OO X  XX': [0],
' OO  XXX ': [0],
' OO  XX X': [0],
' OO  X XX': [0],
' O XXOX  ': [0, 2, 7, 8],
' O XXO X ': [2],
' O XXO  X': [0],
' O XX XO ': [0, 2, 5, 8],
' O XX X O': [0, 2, 5, 7],
' O XX OX ': [5],
' O XX O X': [0, 2, 5, 7],
' O XX  XO': [5],
' O XX  OX': [0, 2, 5, 6],
' O XOXX  ': [7],
' O XOX X ': [0, 2],
' O XOX  X': [7],
' O XO XX ': [0, 2, 5, 8],
' O XO X X': [7],
' O XO  XX': [6],
' O X XXO ': [4],
' O X XX O': [0, 2, 4, 7],
' O X XOX ': [4],
' O X XO X': [0, 2, 4, 7],
' O X X XO': [4],
' O X X OX': [4],
' O X OXX ': [0, 2, 4, 8],
' O X OX X': [0, 2, 4, 7],
' O X O XX': [6],
' O X  XXO': [0],
' O X  XOX': [4],
' O X  OXX': [2],
' O OXXX  ': [2],
' O OXX X ': [0],
' O OXX  X': [0, 2, 6, 7],
' O OX XX ': [0, 2, 5, 8],
' O OX X X': [0, 2, 5, 7],
' O OX  XX': [0, 2, 5, 6],
' O O XXX ': [8],
' O O XX X': [0, 2, 4, 7],
' O O X XX': [0, 2, 4, 6],
' O  XXXO ': [0, 2, 3, 8],
' O  XXX O': [0, 2, 3, 7],
' O  XXOX ': [3],
' O  XXO X': [0, 2, 3, 7],
' O  XX XO': [3],
' O  XX OX': [0, 2, 3, 6],
' O  XOXX ': [0, 2, 3, 8],
' O  XOX X': [0, 2, 3, 7],
' O  XO XX': [0, 2, 3, 6],
' O  X XXO': [2],
' O  X XOX': [0, 2, 3, 5],
' O  X OXX': [0],
' O  OXXX ': [8],
' O  OXX X': [7],
' O  OX XX': [0, 2, 3, 6],
' O   XXXO': [0],
' O   XXOX': [4],
' O   XOXX': [2],
'  XXXOO  ': [0, 1, 7, 8],
'  XXXO O ': [6],
'  XXXO  O': [6],
'  XXX OO ': [8],
'  XXX O O': [7],
'  XXX  OO': [6],
'  XXOXO  ': [8],
'  XXOX O ': [1],
'  XXOX  O': [0],
'  XXOOX  ': [0],
'  XXOO X ': [0, 6],
'  XXOO  X': [0, 1, 6, 7],
'  XXO XO ': [1],
'  XXO X O': [0],
'  XXO OX ': [0, 1, 5, 8],
'  XXO O X': [5],
'  XXO  XO': [0],
'  XXO  OX': [1],
'  XX XOO ': [8],
'  XX XO O': [7],
'  XX X OO': [6],
'  XX OXO ': [0, 1, 4, 8],
'  XX OX O': [0, 1, 4, 7],
'  XX OOX ': [0, 1, 4],
'  XX OO X': [0, 1, 4],
'  XX O XO': [0, 1, 4, 6],
'  XX O OX': [0, 4],
'  XX  XOO': [0, 1, 4, 5],
'  XX  OXO': [1, 4],
'  XX  OOX': [5],
'  XOXXO  ': [0],
'  XOXX O ': [0, 1, 6, 8],
'  XOXX  O': [6],
'  XOXO X ': [0, 1, 6, 8],
'  XOXO  X': [0, 1, 6, 7],
'  XOX OX ': [0],
'  XOX O X': [0],
'  XOX  XO': [0, 1, 5, 6],
'  XOX  OX': [0, 1, 5, 6],
'  XOOXX  ': [8],
'  XOOX X ': [8],
'  XOO XX ': [5],
'  XOO X X': [5],
'  XOO  XX': [5],
'  XO XXO ': [0, 1, 4, 8],
'  XO XX O': [4],
'  XO XOX ': [0],
'  XO X XO': [0],
'  XO OXX ': [4],
'  XO OX X': [4],
'  XO O XX': [4],
'  XO  XXO': [4],
'  XO  XOX': [0, 1, 4, 5],
'  XO  OXX': [0],
'  X XXOO ': [8],
'  X XXO O': [7],
'  X XX OO': [6],
'  X XOOX ': [1],
'  X XOO X': [0],
'  X XO XO': [0, 1, 3, 6],
'  X XO OX': [0, 1, 3, 6],
'  X X OXO': [1],
'  X X OOX': [0, 1, 3, 5],
'  X OXXO ': [1],
'  X OXX O': [0],
'  X OXOX ': [8],
'  X OX XO': [0],
'  X OOXX ': [3],
'  X OOX X': [3],
'  X OO XX': [3],
'  X O XXO': [0],
'  X O XOX': [1],
'  X O OXX': [5],
'  X  XXOO': [4],
'  X  XOXO': [0],
'  X  OXXO': [4],
'  X  OXOX': [4],
'  X  OOXX': [3],
'  OXXOX  ': [8],
'  OXXO X ': [8],
'  OXXO  X': [0],
'  OXX XO ': [0, 1, 5, 8],
'  OXX X O': [5],
'  OXX OX ': [0, 1, 5, 8],
'  OXX O X': [0, 1, 5, 7],
'  OXX  XO': [5],
'  OXX  OX': [0, 1, 5, 6],
'  OXOXX  ': [0],
'  OXOX X ': [6],
'  OXOX  X': [6],
'  OXO XX ': [0, 1, 5, 8],
'  OXO X X': [0, 1, 5, 7],
'  OXO  XX': [6],
'  OX XXO ': [0, 1, 4, 8],
'  OX XX O': [0, 1, 4, 7],
'  OX XOX ': [4],
'  OX XO X': [4],
'  OX X XO': [4],
'  OX X OX': [4],
'  OX OXX ': [8],
'  OX OX X': [0, 1, 4, 7],
'  OX O XX': [6],
'  OX  XXO': [5],
'  OX  XOX': [0],
'  OX  OXX': [4],
'  OOXXX  ': [0, 1, 7, 8],
'  OOXX X ': [1],
'  OOXX  X': [0],
'  OOX XX ': [0, 1, 5, 8],
'  OOX X X': [0, 1, 5, 7],
'  OOX  XX': [0, 1, 5, 6],
'  OO XXX ': [8],
'  OO XX X': [7],
'  OO X XX': [6],
'  O XXXO ': [3],
'  O XXX O': [3],
'  O XXOX ': [0, 1, 3, 8],
'  O XXO X': [0, 1, 3, 7],
'  O XX XO': [0, 1, 3, 6],
'  O XX OX': [0, 1, 3, 6],
'  O XOXX ': [8],
'  O XOX X': [0, 1, 3, 7],
'  O XO XX': [0, 1, 3, 6],
'  O X XXO': [5],
'  O X XOX': [0],
'  O X OXX': [0, 1, 3, 5],
'  O OXXX ': [8],
'  O OXX X': [7],
'  O OX XX': [6],
'  O  XXXO': [0],
'  O  XXOX': [1],
'  O  XOXX': [4],
'   XXOXO ': [0, 1, 2, 8],
'   XXOX O': [2],
'   XXOOX ': [1],
'   XXOO X': [0],
'   XXO XO': [2],
'   XXO OX': [0],
'   XX XOO': [0, 1, 2, 5],
'   XX OXO': [0, 1, 2, 5],
'   XX OOX': [0, 1, 2, 5],
'   XOXXO ': [1],
'   XOXX O': [0],
'   XOXOX ': [2],
'   XOXO X': [2],
'   XOX XO': [0],
'   XOX OX': [1],
'   XOOXX ': [0, 1, 2, 8],
'   XOOX X': [0, 1, 2, 7],
'   XOO XX': [6],
'   XO XXO': [0],
'   XO XOX': [1],
'   XO OXX': [2],
'   X XXOO': [0, 1, 2, 4],
'   X XOXO': [4],
'   X XOOX': [0, 1, 2, 4],
'   X OXXO': [2],
'   X OXOX': [0],
'   X OOXX': [0, 1, 4],
'   OXXXO ': [2],
'   OXXX O': [2],
'   OXXOX ': [0],
'   OXXO X': [0],
'   OXX XO': [1],
'   OXX OX': [0, 1, 2, 6],
'   OXOXX ': [0, 1, 2, 8],
'   OXOX X': [0, 1, 2, 7],
'   OXO XX': [0, 1, 2, 6],
'   OX XXO': [0, 1, 2, 5],
'   OX XOX': [0, 1, 2, 5],
'   OX OXX': [0],
'   OOXXX ': [8],
'   OOXX X': [0, 1, 2, 7],
'   OOX XX': [0, 1, 2, 6],
'   O XXXO': [1, 2, 4],
'   O XXOX': [2],
'   O XOXX': [0],
'    XXXOO': [0, 1, 2, 3],
'    XXOXO': [0, 1, 2, 3],
'    XXOOX': [0, 1, 2, 3],
'    XOXXO': [2],
'    XOXOX': [0, 1, 2, 3],
'    XOOXX': [0, 1, 2, 3],
'    OXXXO': [0],
'    OXXOX': [1],
'    OXOXX': [2]}

book6 = {
'XXOXOO   ': [6],
'XXOXO  O ': [6],
'XXOXO   O': [6],
'XXOX OO  ': [4, 7, 8],
'XXOX O O ': [6],
'XXOX  OO ': [4, 5, 8],
'XXOX  O O': [4, 5, 7],
'XXOX   OO': [6],
'XXOOXO   ': [7, 8],
'XXOOX O  ': [7, 8],
'XXOOX  O ': [8],
'XXOOX   O': [7],
'XXOOOX   ': [6],
'XXOOO X  ': [5],
'XXOOO  X ': [5, 6, 8],
'XXOOO   X': [5, 6, 7],
'XXOO XO  ': [4],
'XXOO X O ': [4, 6, 8],
'XXOO X  O': [4, 6, 7],
'XXOO OX  ': [4, 7, 8],
'XXOO O X ': [4],
'XXOO O  X': [4],
'XXOO  XO ': [4, 5, 8],
'XXOO  X O': [5],
'XXOO  OX ': [4],
'XXOO  O X': [4],
'XXOO   XO': [4],
'XXOO   OX': [4],
'XXO XOO  ': [7, 8],
'XXO XO O ': [8],
'XXO X OO ': [8],
'XXO X O O': [7],
'XXO X  OO': [3, 5, 6],
'XXO OX O ': [6],
'XXO OX  O': [6],
'XXO OOX  ': [3],
'XXO OO X ': [3, 6, 8],
'XXO OO  X': [3, 6, 7],
'XXO O XO ': [3],
'XXO O X O': [3],
'XXO O  XO': [3, 5, 6],
'XXO O  OX': [6],
'XXO  XOO ': [3, 4, 8],
'XXO  XO O': [3, 4, 7],
'XXO  X OO': [6],
'XXO  OXO ': [3],
'XXO  OOX ': [4],
'XXO  OO X': [4],
'XXO  O OX': [4],
'XXO   XOO': [3],
'XXO   OXO': [4],
'XXO   OOX': [4],
'XX XOOO  ': [2],
'XX XOO O ': [2, 6],
'XX XOO  O': [2, 6],
'XX XO OO ': [2],
'XX XO O O': [2],
'XX XO  OO': [2, 6],
'XX X OOO ': [2],
'XX X OO O': [2],
'XX X O OO': [2, 6],
'XX OXOO  ': [2, 7, 8],
'XX OXO O ': [2, 8],
'XX OXO  O': [2, 7],
'XX OX OO ': [2, 8],
'XX OX O O': [2, 7],
'XX OX  OO': [2],
'XX OOXO  ': [2],
'XX OOX O ': [2],
'XX OOX  O': [2],
'XX OO XO ': [2],
'XX OO X O': [2],
'XX OO OX ': [2],
'XX OO O X': [2],
'XX OO  XO': [2],
'XX OO  OX': [2],
'XX O XOO ': [2],
'XX O XO O': [2],
'XX O X OO': [2],
'XX O OXO ': [2],
'XX O OX O': [2],
'XX O OOX ': [2, 4],
'XX O OO X': [2, 4],
'XX O O XO': [2, 4],
'XX O O OX': [2, 4],
'XX O  XOO': [2],
'XX O  OXO': [2, 4],
'XX O  OOX': [2, 4],
'XX  XOOO ': [2, 8],
'XX  XOO O': [2, 7],
'XX  XO OO': [2],
'XX  OXOO ': [2],
'XX  OXO O': [2],
'XX  OX OO': [2],
'XX  OOXO ': [2, 3],
'XX  OOX O': [2, 3],
'XX  OOOX ': [2],
'XX  OOO X': [2],
'XX  OO XO': [2],
'XX  OO OX': [2],
'XX  O XOO': [2, 3],
'XX  O OXO': [2],
'XX  O OOX': [2],
'XX   OXOO': [2, 3],
'XX   OOXO': [2, 4],
'XX   OOOX': [2, 4],
'XOXXOO   ': [6],
'XOXXO O  ': [7],
'XOXXO   O': [6],
'XOXX OO  ': [4, 7, 8],
'XOXX O O ': [6],
'XOXX O  O': [6],
'XOXX  OO ': [4, 5, 8],
'XOXX  O O': [7],
'XOXX   OO': [6],
'XOXOXO   ': [6, 8],
'XOXOX O  ': [8],
'XOXOX  O ': [6, 8],
'XOXOX   O': [6],
'XOXOOX   ': [8],
'XOXOO X  ': [5, 7, 8],
'XOXOO  X ': [5],
'XOXOO   X': [5],
'XOXO XO  ': [8],
'XOXO X O ': [8],
'XOXO X  O': [4, 6, 7],
'XOXO OX  ': [4],
'XOXO O X ': [4],
'XOXO O  X': [4],
'XOXO  XO ': [4],
'XOXO  X O': [4],
'XOXO  OX ': [8],
'XOXO  O X': [4, 5],
'XOXO   XO': [4, 5, 6],
'XOXO   OX': [4, 5],
'XOX XOO  ': [8],
'XOX XO O ': [6, 8],
'XOX XO  O': [6],
'XOX X OO ': [8],
'XOX X O O': [7],
'XOX X  OO': [6],
'XOX OXO  ': [8],
'XOX OX  O': [7],
'XOX OOX  ': [3],
'XOX OO X ': [3],
'XOX OO  X': [3, 6, 7],
'XOX O X O': [3],
'XOX O OX ': [3, 5, 8],
'XOX O O X': [5],
'XOX O  XO': [3, 5, 6],
'XOX  XOO ': [8],
'XOX  XO O': [7],
'XOX  X OO': [3, 4, 6],
'XOX  OXO ': [3, 4],
'XOX  OX O': [3, 4],
'XOX  OOX ': [3, 4, 8],
'XOX  OO X': [4],
'XOX  O XO': [6],
'XOX  O OX': [4],
'XOX   XOO': [3, 4],
'XOX   OXO': [3, 4, 5],
'XOX   OOX': [4, 5],
'XOOXXO   ': [6, 8],
'XOOXX O  ': [5, 8],
'XOOXX  O ': [5, 6, 8],
'XOOXX   O': [5, 6],
'XOOXOX   ': [6],
'XOOXO  X ': [6],
'XOOXO   X': [6],
'XOOX XO  ': [4],
'XOOX X O ': [4, 6],
'XOOX X  O': [4, 6],
'XOOX O X ': [6],
'XOOX O  X': [4, 6],
'XOOX  OX ': [4],
'XOOX  O X': [4],
'XOOX   XO': [6],
'XOOX   OX': [4, 6],
'XOOOXX   ': [8],
'XOOOX X  ': [8],
'XOOOX  X ': [8],
'XOOO XX  ': [8],
'XOOO X X ': [8],
'XOOO X  X': [4],
'XOOO  XX ': [8],
'XOOO  X X': [4, 7],
'XOOO   XX': [4, 6],
'XOO XXO  ': [3, 8],
'XOO XX O ': [3, 8],
'XOO XX  O': [3],
'XOO XOX  ': [3, 8],
'XOO XO X ': [8],
'XOO X XO ': [3, 8],
'XOO X X O': [3],
'XOO X OX ': [8],
'XOO X  XO': [5],
'XOO OXX  ': [3],
'XOO OX X ': [6],
'XOO OX  X': [3, 6, 7],
'XOO O XX ': [3, 8],
'XOO O X X': [3, 7],
'XOO O  XX': [6],
'XOO  XXO ': [3],
'XOO  XX O': [3],
'XOO  XOX ': [4],
'XOO  XO X': [4],
'XOO  X XO': [3],
'XOO  X OX': [4],
'XOO  OXX ': [3, 8],
'XOO  OX X': [3, 4, 7],
'XOO  O XX': [4, 6],
'XOO   XXO': [3],
'XOO   XOX': [3, 4],
'XOO   OXX': [4],
'XO XXOO  ': [8],
'XO XXO O ': [6, 8],
'XO XXO  O': [6],
'XO XX OO ': [5, 8],
'XO XX O O': [5],
'XO XX  OO': [5, 6],
'XO XOXO  ': [2, 7, 8],
'XO XOX  O': [6],
'XO XOO X ': [6],
'XO XOO  X': [6],
'XO XO OX ': [2],
'XO XO O X': [2, 5, 7],
'XO XO  XO': [6],
'XO X XOO ': [4],
'XO X XO O': [4],
'XO X X OO': [4, 6],
'XO X OOX ': [2, 4, 8],
'XO X OO X': [4],
'XO X O XO': [6],
'XO X O OX': [4, 6],
'XO X  OXO': [2, 4, 5],
'XO X  OOX': [4],
'XO OXXO  ': [8],
'XO OXX O ': [8],
'XO OXX  O': [2, 6, 7],
'XO OXOX  ': [2, 8],
'XO OXO X ': [8],
'XO OX XO ': [2, 8],
'XO OX X O': [2],
'XO OX OX ': [8],
'XO OX  XO': [2, 5, 6],
'XO OOXX  ': [7],
'XO OOX X ': [8],
'XO OOX  X': [2],
'XO OO XX ': [8],
'XO OO X X': [7],
'XO OO  XX': [6],
'XO O XXO ': [4],
'XO O XX O': [2, 4, 7],
'XO O XOX ': [8],
'XO O XO X': [2, 4],
'XO O X XO': [2, 4, 6],
'XO O X OX': [2, 4],
'XO O OXX ': [8],
'XO O OX X': [4, 7],
'XO O O XX': [4, 6],
'XO O  XXO': [2, 4, 5],
'XO O  XOX': [4],
'XO O  OXX': [4],
'XO  XXOO ': [3, 8],
'XO  XXO O': [3],
'XO  XX OO': [3],
'XO  XOXO ': [2, 3, 8],
'XO  XOX O': [2, 3],
'XO  XOOX ': [8],
'XO  XO XO': [2],
'XO  X XOO': [2, 3],
'XO  X OXO': [2, 3, 5],
'XO  OXX O': [3],
'XO  OXOX ': [2],
'XO  OXO X': [2],
'XO  OX XO': [2, 3, 6],
'XO  OOXX ': [3, 8],
'XO  OOX X': [3, 7],
'XO  OO XX': [6],
'XO  O XXO': [3],
'XO  O OXX': [2],
'XO   XXOO': [3],
'XO   XOXO': [2, 3, 4],
'XO   XOOX': [2, 4],
'XO   OXXO': [3],
'XO   OXOX': [3, 4],
'XO   OOXX': [4],
'X XXOOO  ': [1],
'X XXOO O ': [1, 6],
'X XXOO  O': [1, 6],
'X XXO OO ': [1],
'X XXO O O': [1],
'X XXO  OO': [1, 6],
'X XX OOO ': [1],
'X XX OO O': [1],
'X XX O OO': [1, 6],
'X XOXOO  ': [1, 8],
'X XOXO O ': [1, 6, 8],
'X XOXO  O': [1, 6],
'X XOX OO ': [1, 8],
'X XOX O O': [1],
'X XOX  OO': [1, 6],
'X XOOXO  ': [1, 8],
'X XOOX O ': [1, 8],
'X XOOX  O': [1],
'X XOO XO ': [1],
'X XOO X O': [1],
'X XOO OX ': [1],
'X XOO O X': [1, 5],
'X XOO  XO': [1],
'X XOO  OX': [1, 5],
'X XO XOO ': [1, 8],
'X XO XO O': [1],
'X XO X OO': [1],
'X XO OXO ': [1, 4],
'X XO OX O': [1, 4],
'X XO OOX ': [1],
'X XO OO X': [1, 4],
'X XO O XO': [1],
'X XO O OX': [1, 4],
'X XO  XOO': [1, 4],
'X XO  OXO': [1],
'X XO  OOX': [1, 4, 5],
'X X XOOO ': [1, 8],
'X X XOO O': [1],
'X X XO OO': [1, 6],
'X X OXOO ': [1, 8],
'X X OXO O': [1],
'X X OX OO': [1],
'X X OOXO ': [1, 3],
'X X OOX O': [1, 3],
'X X OOOX ': [1],
'X X OOO X': [1],
'X X OO XO': [1],
'X X OO OX': [1],
'X X O XOO': [1, 3],
'X X O OXO': [1],
'X X O OOX': [1, 5],
'X X  OXOO': [1, 3, 4],
'X X  OOXO': [1],
'X X  OOOX': [1, 4],
'X OXXOO  ': [8],
'X OXXO O ': [6, 8],
'X OXX OO ': [5, 8],
'X OXX O O': [5],
'X OXX  OO': [5, 6],
'X OXOX O ': [6],
'X OXOX  O': [6],
'X OXOO X ': [6],
'X OXOO  X': [6],
'X OXO  XO': [6],
'X OXO  OX': [6],
'X OX XOO ': [4],
'X OX XO O': [4],
'X OX X OO': [4, 6],
'X OX OOX ': [1, 4, 8],
'X OX OO X': [4],
'X OX O OX': [4, 6],
'X OX  OXO': [1, 4, 5],
'X OX  OOX': [4],
'X OOXXO  ': [8],
'X OOXX O ': [8],
'X OOXX  O': [1, 6, 7],
'X OOXOX  ': [8],
'X OOXO X ': [1, 8],
'X OOX XO ': [8],
'X OOX X O': [5],
'X OOX OX ': [1, 8],
'X OOX  XO': [1],
'X OOOXX  ': [1, 7, 8],
'X OOOX X ': [6],
'X OOOX  X': [6],
'X OOO XX ': [8],
'X OOO X X': [7],
'X OOO  XX': [6],
'X OO XXO ': [1, 4, 8],
'X OO XX O': [1, 4, 7],
'X OO XOX ': [4],
'X OO XO X': [4],
'X OO X XO': [1, 4, 6],
'X OO X OX': [4],
'X OO OXX ': [8],
'X OO OX X': [4, 7],
'X OO O XX': [4, 6],
'X OO  XXO': [5],
'X OO  XOX': [4],
'X OO  OXX': [4],
'X O XXOO ': [3, 8],
'X O XXO O': [3],
'X O XX OO': [3],
'X O XOXO ': [3, 8],
'X O XOOX ': [1, 8],
'X O X XOO': [3],
'X O X OXO': [1],
'X O OXXO ': [3],
'X O OXX O': [3],
'X O OX XO': [6],
'X O OX OX': [1, 3, 6],
'X O OOXX ': [3, 8],
'X O OOX X': [3, 7],
'X O OO XX': [6],
'X O O XXO': [3],
'X O O XOX': [3],
'X O  XXOO': [3],
'X O  XOXO': [4],
'X O  XOOX': [4],
'X O  OXOX': [3, 4],
'X O  OOXX': [4],
'X  XXOOO ': [8],
'X  XXOO O': [1, 2, 7],
'X  XXO OO': [6],
'X  XOXOO ': [1, 2, 8],
'X  XOXO O': [1, 2, 7],
'X  XOX OO': [6],
'X  XOOOX ': [2],
'X  XOOO X': [2],
'X  XOO XO': [6],
'X  XOO OX': [6],
'X  XO OXO': [2],
'X  XO OOX': [1, 2, 5],
'X  X OOXO': [2],
'X  X OOOX': [4],
'X  OXXOO ': [8],
'X  OXXO O': [7],
'X  OXX OO': [6],
'X  OXOXO ': [2, 8],
'X  OXOX O': [2],
'X  OXOOX ': [1, 8],
'X  OXO XO': [1],
'X  OX XOO': [2],
'X  OX OXO': [1],
'X  OOXXO ': [1],
'X  OOXX O': [1, 2, 7],
'X  OOXOX ': [2],
'X  OOXO X': [2],
'X  OOX XO': [1, 2, 6],
'X  OOX OX': [2],
'X  OO XXO': [5],
'X  OO XOX': [1, 2, 5],
'X  OO OXX': [1, 2, 5],
'X  O XXOO': [2],
'X  O XOXO': [1],
'X  O XOOX': [2, 4],
'X  O OXXO': [1, 2, 4],
'X  O OXOX': [4],
'X  O OOXX': [4],
'X   XOXOO': [2, 3],
'X   XOOXO': [1],
'X   OXXOO': [3],
'X   OXOXO': [2],
'X   OXOOX': [2],
'X   OOXXO': [3],
'X   OOXOX': [3],
'X   OOOXX': [1, 2, 3],
'OXXXOO   ': [8],
'OXXXO O  ': [8],
'OXXXO  O ': [8],
'OXXX OO  ': [4, 7, 8],
'OXXX O O ': [4, 6, 8],
'OXXX O  O': [4],
'OXXX  OO ': [8],
'OXXX  O O': [4, 5, 7],
'OXXX   OO': [4, 5, 6],
'OXXOXO   ': [6, 7],
'OXXOX  O ': [6],
'OXXOX   O': [6, 7],
'OXXOOX   ': [8],
'OXXOO X  ': [5, 7, 8],
'OXXOO  X ': [5, 6, 8],
'OXXOO   X': [5],
'OXXO X O ': [8],
'OXXO X  O': [4, 6, 7],
'OXXO OX  ': [4],
'OXXO O X ': [4],
'OXXO O  X': [4, 6, 7],
'OXXO  XO ': [4],
'OXXO  X O': [4],
'OXXO   XO': [4],
'OXXO   OX': [5],
'OXX XOO  ': [7],
'OXX XO O ': [6],
'OXX XO  O': [6, 7],
'OXX X OO ': [3, 5, 8],
'OXX X O O': [7],
'OXX X  OO': [6],
'OXX OXO  ': [8],
'OXX OX O ': [8],
'OXX OOX  ': [3, 7, 8],
'OXX OO X ': [3, 6, 8],
'OXX OO  X': [3],
'OXX O XO ': [8],
'OXX O OX ': [3, 5, 8],
'OXX O O X': [5],
'OXX O  OX': [5],
'OXX  XOO ': [8],
'OXX  XO O': [3, 4, 7],
'OXX  X OO': [3, 4, 6],
'OXX  OXO ': [4],
'OXX  OX O': [4],
'OXX  OOX ': [4],
'OXX  OO X': [3],
'OXX  O XO': [4],
'OXX  O OX': [3, 4, 6],
'OXX   XOO': [4],
'OXX   OXO': [4],
'OXX   OOX': [5],
'OXOXXO   ': [7],
'OXOXX O  ': [5, 7],
'OXOXX  O ': [5],
'OXOXX   O': [5, 7],
'OXOXOX   ': [6, 7, 8],
'OXOXO X  ': [8],
'OXOXO  X ': [5, 6, 8],
'OXOXO   X': [6],
'OXOX XO  ': [4],
'OXOX X O ': [4],
'OXOX X  O': [4],
'OXOX OX  ': [8],
'OXOX O X ': [4],
'OXOX O  X': [7],
'OXOX  XO ': [4, 5, 8],
'OXOX  X O': [4, 5, 7],
'OXOX  OX ': [4],
'OXOX  O X': [4],
'OXOX   XO': [4],
'OXOX   OX': [4, 5, 6],
'OXOOXX   ': [7],
'OXOOX X  ': [7],
'OXOOX   X': [7],
'OXOO XX  ': [7],
'OXOO X X ': [4],
'OXOO X  X': [6],
'OXOO  XX ': [4, 8],
'OXOO  X X': [7],
'OXOO   XX': [4, 6],
'OXO XXO  ': [3, 7],
'OXO XX O ': [3],
'OXO XX  O': [3, 7],
'OXO XOX  ': [7],
'OXO XO  X': [7],
'OXO X XO ': [3, 5, 8],
'OXO X X O': [7],
'OXO X O X': [7],
'OXO X  OX': [3, 5, 6],
'OXO OXX  ': [8],
'OXO OX X ': [3, 6, 8],
'OXO OX  X': [6],
'OXO O XX ': [8],
'OXO O X X': [7],
'OXO O  XX': [6],
'OXO  XXO ': [3, 4, 8],
'OXO  XX O': [4],
'OXO  XOX ': [4],
'OXO  XO X': [3, 4, 7],
'OXO  X XO': [4],
'OXO  X OX': [3, 4, 6],
'OXO  OXX ': [4, 8],
'OXO  OX X': [7],
'OXO  O XX': [4, 6],
'OXO   XXO': [4],
'OXO   XOX': [3, 4, 5],
'OXO   OXX': [4],
'OX XXOO  ': [7],
'OX XXO O ': [2, 6, 8],
'OX XXO  O': [7],
'OX XX OO ': [5],
'OX XX O O': [5, 7],
'OX XX  OO': [5],
'OX XOXO  ': [2, 7, 8],
'OX XOX O ': [8],
'OX XOOX  ': [8],
'OX XOO X ': [8],
'OX XOO  X': [2, 6, 7],
'OX XO XO ': [8],
'OX XO OX ': [2, 5, 8],
'OX XO O X': [2],
'OX XO  OX': [2, 5, 6],
'OX X XOO ': [4],
'OX X XO O': [4],
'OX X X OO': [4],
'OX X OXO ': [2, 4, 8],
'OX X OX O': [2, 4, 7],
'OX X OOX ': [4],
'OX X OO X': [2, 4, 7],
'OX X O XO': [4],
'OX X O OX': [2, 4, 6],
'OX X  XOO': [4],
'OX X  OXO': [4],
'OX X  OOX': [5],
'OX OXX O ': [6],
'OX OXX  O': [7],
'OX OXOX  ': [2, 7],
'OX OXO  X': [7],
'OX OX XO ': [2],
'OX OX X O': [2, 7],
'OX OX  OX': [6],
'OX OOXX  ': [8],
'OX OOX X ': [2, 6, 8],
'OX OOX  X': [2],
'OX OO XX ': [8],
'OX OO X X': [7],
'OX OO  XX': [6],
'OX O XXO ': [2],
'OX O XX O': [4],
'OX O X XO': [4],
'OX O X OX': [2],
'OX O OXX ': [4, 8],
'OX O OX X': [7],
'OX O O XX': [4, 6],
'OX O  XXO': [4],
'OX O  XOX': [2],
'OX  XXOO ': [3],
'OX  XXO O': [3, 7],
'OX  XX OO': [3],
'OX  XOXO ': [2],
'OX  XOX O': [2, 7],
'OX  XOO X': [7],
'OX  XO OX': [2, 3, 6],
'OX  X XOO': [2],
'OX  X OOX': [3],
'OX  OXXO ': [8],
'OX  OXOX ': [2, 3, 8],
'OX  OXO X': [2],
'OX  OX OX': [2],
'OX  OOXX ': [8],
'OX  OOX X': [7],
'OX  OO XX': [6],
'OX  O XOX': [2, 3, 5],
'OX  O OXX': [2, 3, 5],
'OX   XXOO': [4],
'OX   XOXO': [4],
'OX   XOOX': [2],
'OX   OXXO': [4],
'OX   OXOX': [2, 3, 4],
'OX   OOXX': [4],
'OOXXXO   ': [6],
'OOXXX O  ': [5],
'OOXXX  O ': [5, 6],
'OOXXX   O': [5, 6],
'OOXXOX   ': [8],
'OOXXO X  ': [5, 7, 8],
'OOXXO  X ': [8],
'OOXXO   X': [5],
'OOXX XO  ': [4, 8],
'OOXX X O ': [4, 8],
'OOXX X  O': [4],
'OOXX OX  ': [4],
'OOXX O X ': [6],
'OOXX O  X': [6],
'OOXX  XO ': [4],
'OOXX  X O': [4],
'OOXX  OX ': [5],
'OOXX  O X': [5],
'OOXX   XO': [4],
'OOXX   OX': [5],
'OOXOXX   ': [6, 8],
'OOXOX  X ': [6],
'OOXOX   X': [5, 6],
'OOXO XX  ': [4, 8],
'OOXO X X ': [8],
'OOXO  XX ': [4, 8],
'OOXO  X X': [4, 5, 7],
'OOXO   XX': [5, 6],
'OOX XXO  ': [3, 8],
'OOX XX O ': [3, 6, 8],
'OOX XX  O': [3, 6],
'OOX XO X ': [6],
'OOX XO  X': [6],
'OOX X OX ': [3],
'OOX X O X': [5],
'OOX X  XO': [6],
'OOX X  OX': [5, 6],
'OOX OXX  ': [8],
'OOX OX X ': [8],
'OOX O XX ': [8],
'OOX O X X': [5, 7],
'OOX O  XX': [5, 6],
'OOX  XXO ': [4, 8],
'OOX  XX O': [4],
'OOX  XOX ': [8],
'OOX  X XO': [4],
'OOX  OXX ': [4, 8],
'OOX  OX X': [4, 7],
'OOX  O XX': [6],
'OOX   XXO': [4],
'OOX   XOX': [4, 5],
'OOX   OXX': [5],
'OO XXOX  ': [2],
'OO XXO X ': [2],
'OO XXO  X': [2],
'OO XX XO ': [2, 5],
'OO XX X O': [2, 5],
'OO XX OX ': [5],
'OO XX O X': [5],
'OO XX  XO': [5],
'OO XX  OX': [5],
'OO XOXX  ': [2, 7, 8],
'OO XOX X ': [2, 6, 8],
'OO XOX  X': [2],
'OO XO XX ': [8],
'OO XO X X': [7],
'OO XO  XX': [6],
'OO X XXO ': [4],
'OO X XX O': [4],
'OO X XOX ': [4],
'OO X XO X': [2, 4],
'OO X X XO': [4],
'OO X X OX': [2, 4],
'OO X OXX ': [8],
'OO X OX X': [7],
'OO X O XX': [6],
'OO X  XXO': [2, 4, 5],
'OO X  XOX': [2, 4, 5],
'OO X  OXX': [2],
'OO OXXX  ': [2],
'OO OXX X ': [2, 6, 8],
'OO OXX  X': [2],
'OO OX XX ': [2, 8],
'OO OX X X': [2, 7],
'OO OX  XX': [6],
'OO O XXX ': [8],
'OO O XX X': [2, 7],
'OO O X XX': [2, 6],
'OO  XXXO ': [2, 3],
'OO  XXX O': [2, 3],
'OO  XXOX ': [3],
'OO  XXO X': [2, 3],
'OO  XX XO': [3],
'OO  XX OX': [2, 3],
'OO  XOXX ': [2, 8],
'OO  XOX X': [2, 7],
'OO  XO XX': [6],
'OO  X XXO': [2],
'OO  X XOX': [2],
'OO  X OXX': [2, 3, 5],
'OO  OXXX ': [8],
'OO  OXX X': [2, 7],
'OO  OX XX': [2, 6],
'OO   XXXO': [2, 3, 4],
'OO   XXOX': [2],
'OO   XOXX': [2],
'O XXXOO  ': [1, 7, 8],
'O XXXO O ': [6],
'O XXXO  O': [6],
'O XXX OO ': [5],
'O XXX O O': [5],
'O XXX  OO': [5, 6],
'O XXOXO  ': [8],
'O XXOX O ': [8],
'O XXOOX  ': [8],
'O XXOO X ': [8],
'O XXOO  X': [1, 6, 7],
'O XXO XO ': [1, 5, 8],
'O XXO OX ': [8],
'O XXO O X': [5],
'O XXO  OX': [5],
'O XX XOO ': [4, 8],
'O XX XO O': [4],
'O XX X OO': [4],
'O XX OXO ': [4],
'O XX OX O': [4],
'O XX OOX ': [1, 4, 8],
'O XX OO X': [1, 4, 7],
'O XX O XO': [4],
'O XX O OX': [1, 4, 6],
'O XX  XOO': [4],
'O XX  OXO': [4],
'O XX  OOX': [5],
'O XOXX O ': [6, 8],
'O XOXX  O': [6],
'O XOXO X ': [1, 6],
'O XOXO  X': [6],
'O XOX  XO': [1, 6],
'O XOX  OX': [5, 6],
'O XOOXX  ': [8],
'O XOOX X ': [8],
'O XOO XX ': [8],
'O XOO X X': [5, 7],
'O XOO  XX': [5, 6],
'O XO XXO ': [4, 8],
'O XO XX O': [4],
'O XO X XO': [1, 4, 6],
'O XO OXX ': [4, 8],
'O XO OX X': [4, 7],
'O XO O XX': [6],
'O XO  XXO': [4],
'O XO  XOX': [4, 5],
'O X XXOO ': [3, 8],
'O X XXO O': [3],
'O X XX OO': [3, 6],
'O X XOOX ': [1],
'O X XOO X': [3],
'O X XO XO': [1, 6],
'O X XO OX': [6],
'O X X OXO': [1],
'O X X OOX': [5],
'O X OXXO ': [8],
'O X OXOX ': [8],
'O X OOXX ': [8],
'O X OOX X': [7],
'O X OO XX': [6],
'O X O XOX': [5],
'O X O OXX': [5],
'O X  XXOO': [4],
'O X  XOXO': [1, 3, 4],
'O X  OXXO': [4],
'O X  OXOX': [4],
'O X  OOXX': [3],
'O OXXOX  ': [1, 7, 8],
'O OXXO X ': [1],
'O OXXO  X': [1],
'O OXX XO ': [5],
'O OXX X O': [5],
'O OXX OX ': [1, 5],
'O OXX O X': [5],
'O OXX  XO': [1, 5],
'O OXX  OX': [5],
'O OXOXX  ': [1, 7, 8],
'O OXOX X ': [1, 6, 8],
'O OXOX  X': [1, 6, 7],
'O OXO XX ': [8],
'O OXO X X': [7],
'O OXO  XX': [6],
'O OX XXO ': [4],
'O OX XX O': [4],
'O OX XOX ': [4],
'O OX XO X': [4],
'O OX X XO': [4],
'O OX X OX': [4],
'O OX OXX ': [8],
'O OX OX X': [7],
'O OX O XX': [6],
'O OX  XXO': [1, 4, 5],
'O OX  XOX': [1],
'O OX  OXX': [1, 4, 5],
'O OOXXX  ': [1],
'O OOXX X ': [1],
'O OOXX  X': [1, 6, 7],
'O OOX XX ': [1, 8],
'O OOX X X': [7],
'O OOX  XX': [1, 6],
'O OO XXX ': [8],
'O OO XX X': [7],
'O OO X XX': [6],
'O O XXXO ': [3],
'O O XXX O': [3],
'O O XXOX ': [1, 3],
'O O XXO X': [3],
'O O XX XO': [1, 3],
'O O XX OX': [3],
'O O XOXX ': [1, 8],
'O O XOX X': [7],
'O O XO XX': [1, 6],
'O O X XXO': [1],
'O O X XOX': [1],
'O O X OXX': [1],
'O O OXXX ': [8],
'O O OXX X': [7],
'O O OX XX': [6],
'O O  XXXO': [1, 3, 4],
'O O  XXOX': [1],
'O O  XOXX': [1, 3, 4],
'O  XXOXO ': [2],
'O  XXOX O': [2],
'O  XXOOX ': [1],
'O  XXOO X': [1, 2, 7],
'O  XXO XO': [1],
'O  XXO OX': [1, 2, 6],
'O  XX XOO': [2, 5],
'O  XX OXO': [1, 5],
'O  XX OOX': [5],
'O  XOXXO ': [1, 2, 8],
'O  XOXOX ': [1, 2, 8],
'O  XOXO X': [2],
'O  XOX OX': [2],
'O  XOOXX ': [8],
'O  XOOX X': [7],
'O  XOO XX': [6],
'O  XO XOX': [1],
'O  XO OXX': [2],
'O  X XXOO': [4],
'O  X XOXO': [4],
'O  X XOOX': [2, 4],
'O  X OXXO': [1, 2, 4],
'O  X OXOX': [1, 2, 4],
'O  X OOXX': [1, 2, 4],
'O  OXXXO ': [2],
'O  OXXX O': [2],
'O  OXX XO': [1],
'O  OXX OX': [2],
'O  OXOXX ': [1, 2, 8],
'O  OXOX X': [2, 7],
'O  OXO XX': [1, 6],
'O  OX XXO': [1, 2],
'O  OX XOX': [2],
'O  OOXXX ': [8],
'O  OOXX X': [2, 7],
'O  OOX XX': [2, 6],
'O  O XXXO': [4],
'O  O XXOX': [2],
'O   XXXOO': [2, 3],
'O   XXOXO': [1, 3],
'O   XXOOX': [2, 3],
'O   XOXXO': [1, 2],
'O   XOXOX': [2],
'O   XOOXX': [1],
'O   OXXOX': [2],
'O   OXOXX': [2],
' XXXOOO  ': [0],
' XXXOO O ': [0],
' XXXOO  O': [0],
' XXXO OO ': [0],
' XXXO O O': [0],
' XXXO  OO': [0],
' XXX OOO ': [0],
' XXX OO O': [0],
' XXX O OO': [0],
' XXOXOO  ': [0, 7],
' XXOXO O ': [0, 6],
' XXOXO  O': [0, 6, 7],
' XXOX OO ': [0],
' XXOX O O': [0, 7],
' XXOX  OO': [0, 6],
' XXOOXO  ': [0, 8],
' XXOOX O ': [0, 8],
' XXOOX  O': [0],
' XXOO XO ': [0],
' XXOO X O': [0],
' XXOO OX ': [0],
' XXOO O X': [0, 5],
' XXOO  XO': [0],
' XXOO  OX': [0, 5],
' XXO XOO ': [0, 8],
' XXO XO O': [0],
' XXO X OO': [0],
' XXO OXO ': [0, 4],
' XXO OX O': [0, 4],
' XXO OOX ': [0, 4],
' XXO OO X': [0],
' XXO O XO': [0, 4],
' XXO O OX': [0],
' XXO  XOO': [0, 4],
' XXO  OXO': [0, 4],
' XXO  OOX': [0, 5],
' XX XOOO ': [0],
' XX XOO O': [0, 7],
' XX XO OO': [0, 6],
' XX OXOO ': [0, 8],
' XX OXO O': [0],
' XX OX OO': [0],
' XX OOXO ': [0],
' XX OOX O': [0],
' XX OOOX ': [0],
' XX OOO X': [0],
' XX OO XO': [0],
' XX OO OX': [0],
' XX O XOO': [0],
' XX O OXO': [0],
' XX O OOX': [0, 5],
' XX  OXOO': [0, 4],
' XX  OOXO': [0, 4],
' XX  OOOX': [0],
' XOXXOO  ': [7],
' XOXXO O ': [8],
' XOXX OO ': [5],
' XOXX O O': [5, 7],
' XOXX  OO': [5],
' XOXOX O ': [6],
' XOXOX  O': [0, 6, 7],
' XOXOOX  ': [0],
' XOXOO X ': [0, 6, 8],
' XOXOO  X': [6],
' XOXO XO ': [0],
' XOXO X O': [0],
' XOXO  XO': [0, 5, 6],
' XOXO  OX': [6],
' XOX XOO ': [4],
' XOX XO O': [4],
' XOX X OO': [4],
' XOX OXO ': [0],
' XOX OOX ': [4],
' XOX OO X': [4],
' XOX O OX': [0],
' XOX  XOO': [0],
' XOX  OXO': [4],
' XOX  OOX': [4],
' XOOXXO  ': [7],
' XOOXX O ': [0, 6, 8],
' XOOXX  O': [7],
' XOOXOX  ': [7],
' XOOXO  X': [0, 7],
' XOOX XO ': [0, 5, 8],
' XOOX X O': [7],
' XOOX O X': [0, 7],
' XOOX  OX': [0],
' XOOOXX  ': [0, 7, 8],
' XOOOX X ': [6],
' XOOOX  X': [6],
' XOOO XX ': [8],
' XOOO X X': [7],
' XOOO  XX': [6],
' XOO XXO ': [0, 4, 8],
' XOO XX O': [0, 4, 7],
' XOO XOX ': [4],
' XOO XO X': [0, 4, 7],
' XOO X XO': [4],
' XOO X OX': [0, 4, 6],
' XOO OXX ': [4, 8],
' XOO OX X': [7],
' XOO O XX': [4, 6],
' XOO  XXO': [4],
' XOO  XOX': [0, 4, 5],
' XOO  OXX': [4],
' XO XXOO ': [3],
' XO XXO O': [3, 7],
' XO XX OO': [3],
' XO XOXO ': [8],
' XO XOO X': [0, 7],
' XO XO OX': [0],
' XO X XOO': [5],
' XO X OOX': [0],
' XO OXXO ': [0, 3, 8],
' XO OXX O': [0],
' XO OX XO': [0, 3, 6],
' XO OX OX': [6],
' XO OOXX ': [8],
' XO OOX X': [7],
' XO OO XX': [6],
' XO O XXO': [0, 3, 5],
' XO O XOX': [0, 3, 5],
' XO  XXOO': [3],
' XO  XOXO': [4],
' XO  XOOX': [4],
' XO  OXOX': [0],
' XO  OOXX': [4],
' X XXOOO ': [8],
' X XXOO O': [7],
' X XXO OO': [0, 2, 6],
' X XOXOO ': [0, 2, 8],
' X XOXO O': [0, 2, 7],
' X XOX OO': [0, 2, 6],
' X XOOXO ': [0],
' X XOOX O': [0],
' X XOOOX ': [2],
' X XOOO X': [2],
' X XOO XO': [0, 2, 6],
' X XOO OX': [0],
' X XO XOO': [0],
' X XO OXO': [0, 2, 5],
' X XO OOX': [2],
' X X OXOO': [0],
' X X OOXO': [4],
' X X OOOX': [0],
' X OXXOO ': [0, 2, 8],
' X OXXO O': [7],
' X OXX OO': [6],
' X OXOXO ': [2],
' X OXOX O': [2, 7],
' X OXOO X': [0, 7],
' X OXO OX': [0],
' X OX XOO': [2],
' X OX OOX': [0],
' X OOXXO ': [2],
' X OOXX O': [0],
' X OOXOX ': [0, 2, 8],
' X OOXO X': [2],
' X OOX XO': [0],
' X OOX OX': [2],
' X OO XXO': [0, 2, 5],
' X OO XOX': [5],
' X OO OXX': [0, 2, 5],
' X O XXOO': [2],
' X O XOXO': [4],
' X O XOOX': [2],
' X O OXXO': [4],
' X O OXOX': [4],
' X O OOXX': [4],
' X  XOXOO': [2],
' X  XOOOX': [0],
' X  OXXOO': [0],
' X  OXOXO': [0, 2, 3],
' X  OXOOX': [2],
' X  OOXXO': [0, 2, 3],
' X  OOXOX': [3],
' X  OOOXX': [0, 2, 3],
' OXXXOO  ': [0, 7, 8],
' OXXXO O ': [6],
' OXXXO  O': [6],
' OXXX OO ': [5],
' OXXX O O': [5],
' OXXX  OO': [5, 6],
' OXXOXO  ': [8],
' OXXOX  O': [0, 6, 7],
' OXXOOX  ': [0],
' OXXOO X ': [6],
' OXXOO  X': [7],
' OXXO X O': [0],
' OXXO OX ': [0, 5, 8],
' OXXO O X': [5],
' OXXO  XO': [0],
' OXX XOO ': [4, 8],
' OXX XO O': [4],
' OXX X OO': [4],
' OXX OXO ': [0, 4],
' OXX OX O': [0, 4],
' OXX OOX ': [0, 4, 8],
' OXX OO X': [0, 4, 7],
' OXX O XO': [6],
' OXX O OX': [4],
' OXX  XOO': [0, 4],
' OXX  OXO': [0, 4, 5],
' OXX  OOX': [5],
' OXOXXO  ': [8],
' OXOXX O ': [6, 8],
' OXOXX  O': [6],
' OXOXO X ': [6],
' OXOXO  X': [0, 6],
' OXOX OX ': [0],
' OXOX O X': [0, 5],
' OXOX  XO': [6],
' OXOX  OX': [0, 5, 6],
' OXOOXX  ': [8],
' OXOOX X ': [8],
' OXOO XX ': [8],
' OXOO X X': [5, 7],
' OXOO  XX': [5, 6],
' OXO XXO ': [4, 8],
' OXO XX O': [4],
' OXO XOX ': [8],
' OXO X XO': [0, 4, 6],
' OXO OXX ': [4, 8],
' OXO OX X': [4, 7],
' OXO O XX': [6],
' OXO  XXO': [4],
' OXO  XOX': [4, 5],
' OXO  OXX': [5],
' OX XXOO ': [3, 8],
' OX XXO O': [3],
' OX XX OO': [3, 6],
' OX XOOX ': [0, 3, 8],
' OX XOO X': [0],
' OX XO XO': [6],
' OX XO OX': [0, 6],
' OX X OXO': [0, 3, 5],
' OX X OOX': [0, 5],
' OX OXX O': [0, 3, 7],
' OX OXOX ': [8],
' OX OX XO': [0],
' OX OOXX ': [8],
' OX OOX X': [7],
' OX OO XX': [6],
' OX O XXO': [0],
' OX O OXX': [5],
' OX  XXOO': [4],
' OX  XOXO': [0, 3, 4],
' OX  OXXO': [4],
' OX  OXOX': [4],
' OX  OOXX': [0, 3, 4],
' OOXXOX  ': [0],
' OOXXO X ': [0, 6, 8],
' OOXXO  X': [0],
' OOXX XO ': [0, 5],
' OOXX X O': [0, 5],
' OOXX OX ': [5],
' OOXX O X': [0, 5],
' OOXX  XO': [5],
' OOXX  OX': [0, 5],
' OOXOXX  ': [0],
' OOXOX X ': [0, 6, 8],
' OOXOX  X': [0, 6, 7],
' OOXO XX ': [0, 8],
' OOXO X X': [0, 7],
' OOXO  XX': [6],
' OOX XXO ': [0, 4],
' OOX XX O': [0, 4],
' OOX XOX ': [4],
' OOX XO X': [4],
' OOX X XO': [4],
' OOX X OX': [4],
' OOX OXX ': [0, 8],
' OOX OX X': [0, 7],
' OOX O XX': [6],
' OOX  XXO': [0],
' OOX  XOX': [0],
' OOX  OXX': [0, 4, 5],
' OOOXXX  ': [0],
' OOOXX X ': [0],
' OOOXX  X': [0],
' OOOX XX ': [8],
' OOOX X X': [0, 7],
' OOOX  XX': [0, 6],
' OOO XXX ': [8],
' OOO XX X': [7],
' OOO X XX': [6],
' OO XXXO ': [3],
' OO XXX O': [3],
' OO XXOX ': [3],
' OO XXO X': [0, 3],
' OO XX XO': [3],
' OO XX OX': [0, 3],
' OO XOXX ': [8],
' OO XOX X': [0, 7],
' OO XO XX': [0, 6],
' OO X XXO': [0, 3, 5],
' OO X XOX': [0],
' OO X OXX': [0],
' OO OXXX ': [8],
' OO OXX X': [7],
' OO OX XX': [6],
' OO  XXXO': [0],
' OO  XXOX': [0, 3, 4],
' OO  XOXX': [0, 3, 4],
' O XXOXO ': [0, 2],
' O XXOX O': [0, 2],
' O XXOOX ': [0, 2, 8],
' O XXOO X': [0],
' O XXO XO': [2],
' O XXO OX': [0],
' O XX XOO': [0, 2, 5],
' O XX OXO': [5],
' O XX OOX': [0, 5],
' O XOXX O': [0],
' O XOXOX ': [2],
' O XOXO X': [2],
' O XOX XO': [0],
' O XOOXX ': [0, 8],
' O XOOX X': [0, 7],
' O XOO XX': [6],
' O XO XXO': [0],
' O XO OXX': [2],
' O X XXOO': [0, 4],
' O X XOXO': [4],
' O X XOOX': [2, 4],
' O X OXXO': [0],
' O X OXOX': [0],
' O X OOXX': [0, 2, 4],
' O OXXXO ': [2],
' O OXXX O': [2],
' O OXXOX ': [0],
' O OXXO X': [0, 2],
' O OXX XO': [0, 2, 6],
' O OXX OX': [0, 2],
' O OXOXX ': [2, 8],
' O OXOX X': [0, 2, 7],
' O OXO XX': [0, 6],
' O OX XXO': [2],
' O OX XOX': [0, 2],
' O OX OXX': [0],
' O OOXXX ': [8],
' O OOXX X': [2, 7],
' O OOX XX': [2, 6],
' O O XXXO': [0, 2, 4],
' O O XXOX': [2],
' O O XOXX': [2],
' O  XXXOO': [2, 3],
' O  XXOXO': [3],
' O  XXOOX': [0, 2, 3],
' O  XOXXO': [2],
' O  XOXOX': [0, 2],
' O  XOOXX': [0],
' O  OXXXO': [0],
' O  OXOXX': [2],
'  XXXOOO ': [8],
'  XXXOO O': [7],
'  XXXO OO': [6],
'  XXOXOO ': [8],
'  XXOXO O': [0, 1, 7],
'  XXOX OO': [0, 1, 6],
'  XXOOXO ': [0],
'  XXOOX O': [0],
'  XXOOOX ': [0, 1, 8],
'  XXOOO X': [0, 1, 7],
'  XXOO XO': [0],
'  XXOO OX': [1],
'  XXO XOO': [0],
'  XXO OXO': [0],
'  XXO OOX': [5],
'  XX OXOO': [0, 4],
'  XX OOXO': [1],
'  XX OOOX': [0],
'  XOXXOO ': [8],
'  XOXXO O': [0, 1, 7],
'  XOXX OO': [6],
'  XOXOOX ': [1],
'  XOXOO X': [0],
'  XOXO XO': [1, 6],
'  XOXO OX': [0, 6],
'  XOX OXO': [1],
'  XOX OOX': [0, 5],
'  XOOXXO ': [8],
'  XOOXX O': [0],
'  XOOXOX ': [8],
'  XOOX XO': [0],
'  XOO XXO': [0, 1, 5],
'  XOO XOX': [5],
'  XOO OXX': [5],
'  XO XXOO': [4],
'  XO XOXO': [0],
'  XO OXXO': [4],
'  XO OXOX': [4],
'  XO OOXX': [0, 1, 4],
'  X XOOXO': [1],
'  X XOOOX': [0],
'  X OXXOO': [0, 1, 3],
'  X OXOXO': [0],
'  X OOXXO': [0, 1, 3],
'  X OOXOX': [0, 1, 3],
'  X OOOXX': [3],
'  OXXOXO ': [0],
'  OXXOOX ': [1],
'  OXXOO X': [0],
'  OXXO OX': [0],
'  OXX XOO': [0, 5],
'  OXX OXO': [1, 5],
'  OXX OOX': [0, 5],
'  OXOXXO ': [0],
'  OXOXX O': [0],
'  OXOX XO': [0, 1, 6],
'  OXOX OX': [0, 1, 6],
'  OXOOXX ': [0, 8],
'  OXOOX X': [0, 7],
'  OXOO XX': [6],
'  OXO XXO': [0],
'  OXO XOX': [0],
'  OX XXOO': [0, 4],
'  OX XOXO': [4],
'  OX XOOX': [4],
'  OX OXOX': [0],
'  OX OOXX': [4],
'  OOXXXO ': [0, 1, 8],
'  OOXXX O': [0, 1, 7],
'  OOXXOX ': [1],
'  OOXXO X': [0],
'  OOXX XO': [1],
'  OOXX OX': [0],
'  OOXOXX ': [1, 8],
'  OOXOX X': [0, 7],
'  OOXO XX': [0, 1, 6],
'  OOX XXO': [1],
'  OOX XOX': [0],
'  OOX OXX': [0, 1],
'  OOOXXX ': [8],
'  OOOXX X': [7],
'  OOOX XX': [6],
'  OO XXXO': [0, 1, 4],
'  OO XXOX': [0, 1, 4],
'  OO XOXX': [0, 1, 4],
'  O XXXOO': [3],
'  O XXOXO': [1, 3],
'  O XXOOX': [0, 3],
'  O XOXOX': [0],
'  O XOOXX': [0, 1],
'  O OXXXO': [0],
'  O OXXOX': [1],
'   XXOXOO': [0, 2],
'   XXOOXO': [1],
'   XXOOOX': [0],
'   XOXXOO': [0],
'   XOXOXO': [0, 1, 2],
'   XOXOOX': [2],
'   XOOXXO': [0],
'   XOOXOX': [0],
'   XOOOXX': [2],
'   OXXXOO': [2],
'   OXXOXO': [1],
'   OXXOOX': [0, 2],
'   OXOXXO': [1, 2],
'   OXOXOX': [0, 2],
'   OXOOXX': [0, 1],
'   OOXXXO': [0],
'   OOXXOX': [2],
'   OOXOXX': [2]}

book7 = {
'XXOXXOO  ': [8],
'XXOXXO O ': [8],
'XXOXX OO ': [8],
'XXOXX O O': [5, 7],
'XXOXX  OO': [5, 6],
'XXOXOX O ': [6],
'XXOXOX  O': [6],
'XXOXOO X ': [6, 8],
'XXOXOO  X': [6],
'XXOXO  XO': [5, 6],
'XXOXO  OX': [6],
'XXOX XOO ': [4, 8],
'XXOX XO O': [4, 7],
'XXOX X OO': [6],
'XXOX OOX ': [4, 8],
'XXOX OO X': [4],
'XXOX O OX': [4, 6],
'XXOX  OXO': [4, 5],
'XXOX  OOX': [4],
'XXOOXXO  ': [7, 8],
'XXOOXX O ': [8],
'XXOOXX  O': [7],
'XXOOXOX  ': [8],
'XXOOX XO ': [8],
'XXOOX X O': [5],
'XXOOOXX  ': [7, 8],
'XXOOOX X ': [6],
'XXOOOX  X': [6],
'XXOOO XX ': [5],
'XXOOO X X': [5],
'XXOOO  XX': [5, 6],
'XXOO XXO ': [4, 8],
'XXOO XX O': [4, 7],
'XXOO XOX ': [4],
'XXOO XO X': [4],
'XXOO X XO': [4],
'XXOO X OX': [4],
'XXOO OXX ': [4, 8],
'XXOO OX X': [4],
'XXOO O XX': [4],
'XXOO  XXO': [5],
'XXOO  XOX': [4],
'XXOO  OXX': [4],
'XXO XXOO ': [8],
'XXO XXO O': [7],
'XXO XX OO': [6],
'XXO XOXO ': [8],
'XXO X XOO': [5],
'XXO OXXO ': [3],
'XXO OXX O': [3],
'XXO OX XO': [6],
'XXO OX OX': [6],
'XXO OOXX ': [3, 8],
'XXO OOX X': [3],
'XXO OO XX': [3, 6],
'XXO O XXO': [5],
'XXO O XOX': [3],
'XXO  XXOO': [3],
'XXO  XOXO': [4],
'XXO  XOOX': [4],
'XXO  OXOX': [3, 4],
'XXO  OOXX': [4],
'XX XXOOO ': [8],
'XX XXOO O': [2, 7],
'XX XXO OO': [2, 6],
'XX XOXOO ': [2, 8],
'XX XOXO O': [2, 7],
'XX XOX OO': [6],
'XX XOOOX ': [2],
'XX XOOO X': [2],
'XX XOO XO': [2],
'XX XOO OX': [2, 6],
'XX XO OXO': [2],
'XX XO OOX': [2],
'XX X OOXO': [2],
'XX X OOOX': [2, 4],
'XX OXXOO ': [8],
'XX OXXO O': [7],
'XX OXX OO': [6],
'XX OXOXO ': [2, 8],
'XX OXOX O': [2],
'XX OX XOO': [2],
'XX OOXXO ': [2],
'XX OOXX O': [2],
'XX OOXOX ': [2],
'XX OOXO X': [2],
'XX OOX XO': [2],
'XX OOX OX': [2],
'XX OO XXO': [5],
'XX OO XOX': [5],
'XX OO OXX': [2, 5],
'XX O XXOO': [2],
'XX O XOXO': [2, 4],
'XX O XOOX': [2, 4],
'XX O OXXO': [2, 4],
'XX O OXOX': [4],
'XX O OOXX': [4],
'XX  XOXOO': [2],
'XX  OXXOO': [2, 3],
'XX  OXOXO': [2],
'XX  OXOOX': [2],
'XX  OOXXO': [2, 3],
'XX  OOXOX': [3],
'XX  OOOXX': [2, 3],
'XOXXXOO  ': [8],
'XOXXXO O ': [6, 8],
'XOXXXO  O': [6],
'XOXXX OO ': [8],
'XOXXX O O': [7],
'XOXXX  OO': [6],
'XOXXOXO  ': [7],
'XOXXOX  O': [7],
'XOXXOO X ': [6],
'XOXXOO  X': [7],
'XOXXO OX ': [5, 8],
'XOXXO O X': [7],
'XOXXO  XO': [6],
'XOXX XOO ': [4, 8],
'XOXX XO O': [7],
'XOXX X OO': [4, 6],
'XOXX OOX ': [4, 8],
'XOXX OO X': [4],
'XOXX O XO': [6],
'XOXX O OX': [4],
'XOXX  OXO': [4, 5],
'XOXX  OOX': [4],
'XOXOXXO  ': [8],
'XOXOXX O ': [6, 8],
'XOXOXX  O': [6],
'XOXOXO X ': [6, 8],
'XOXOX OX ': [8],
'XOXOX  XO': [6],
'XOXOOXX  ': [7],
'XOXOOX X ': [8],
'XOXOO XX ': [5],
'XOXOO X X': [5, 7],
'XOXOO  XX': [5],
'XOXO XXO ': [4],
'XOXO XX O': [4],
'XOXO XOX ': [8],
'XOXO X XO': [4, 6],
'XOXO OXX ': [4],
'XOXO OX X': [4],
'XOXO O XX': [4],
'XOXO  XXO': [4],
'XOXO  XOX': [4],
'XOXO  OXX': [4, 5],
'XOX XXOO ': [8],
'XOX XXO O': [7],
'XOX XX OO': [6],
'XOX XOOX ': [8],
'XOX XO XO': [6],
'XOX X OXO': [3, 5],
'XOX OXX O': [7],
'XOX OXOX ': [8],
'XOX OX XO': [3, 6],
'XOX OOXX ': [3],
'XOX OOX X': [3, 7],
'XOX OO XX': [3],
'XOX O XXO': [3],
'XOX O OXX': [5],
'XOX  XXOO': [4],
'XOX  XOXO': [3, 4],
'XOX  OXXO': [3, 4],
'XOX  OXOX': [4],
'XOX  OOXX': [4],
'XOOXXO X ': [8],
'XOOXX OX ': [5, 8],
'XOOXX  XO': [5],
'XOOXOX X ': [6],
'XOOXOX  X': [6, 7],
'XOOXO  XX': [6],
'XOOX XOX ': [4],
'XOOX XO X': [4],
'XOOX X XO': [4, 6],
'XOOX X OX': [4],
'XOOX O XX': [4, 6],
'XOOX  OXX': [4],
'XOOOXXX  ': [8],
'XOOOXX X ': [8],
'XOOOX XX ': [8],
'XOOO XXX ': [8],
'XOOO XX X': [4, 7],
'XOOO X XX': [4, 6],
'XOO XXXO ': [3, 8],
'XOO XXX O': [3],
'XOO XXOX ': [3, 8],
'XOO XX XO': [3],
'XOO XOXX ': [8],
'XOO X XXO': [5],
'XOO OXXX ': [3, 8],
'XOO OXX X': [7],
'XOO OX XX': [6],
'XOO  XXXO': [3],
'XOO  XXOX': [4],
'XOO  XOXX': [4],
'XO XXOOX ': [8],
'XO XXO XO': [2],
'XO XX OXO': [5],
'XO XOXOX ': [2],
'XO XOXO X': [2, 7],
'XO XOX XO': [6],
'XO XOO XX': [6],
'XO XO OXX': [2],
'XO X XOXO': [4],
'XO X XOOX': [4],
'XO X OOXX': [4],
'XO OXXXO ': [2, 8],
'XO OXXX O': [2],
'XO OXXOX ': [8],
'XO OXX XO': [2, 6],
'XO OXOXX ': [2, 8],
'XO OX XXO': [2],
'XO OOXXX ': [8],
'XO OOXX X': [7],
'XO OOX XX': [2, 6],
'XO O XXXO': [2, 4],
'XO O XXOX': [4],
'XO O XOXX': [2, 4],
'XO  XXXOO': [2, 3],
'XO  XXOXO': [3],
'XO  XOXXO': [2],
'XO  OXXXO': [3],
'XO  OXOXX': [2],
'X XXXOOO ': [8],
'X XXXOO O': [7],
'X XXXO OO': [6],
'X XXOXOO ': [1, 8],
'X XXOXO O': [7],
'X XXOX OO': [1, 6],
'X XXOOOX ': [1],
'X XXOOO X': [1],
'X XXOO XO': [1, 6],
'X XXOO OX': [1],
'X XXO OXO': [1],
'X XXO OOX': [1],
'X XX OOXO': [1],
'X XX OOOX': [1, 4],
'X XOXXOO ': [8],
'X XOXXO O': [7],
'X XOXX OO': [6],
'X XOXOOX ': [1, 8],
'X XOXO XO': [1, 6],
'X XOX OXO': [1],
'X XOOXXO ': [1],
'X XOOXX O': [1],
'X XOOXOX ': [1, 8],
'X XOOX XO': [1],
'X XOO XXO': [5],
'X XOO XOX': [1, 5],
'X XOO OXX': [5],
'X XO XXOO': [1, 4],
'X XO XOXO': [1],
'X XO OXXO': [4],
'X XO OXOX': [4],
'X XO OOXX': [4],
'X X XOOXO': [1],
'X X OXXOO': [1],
'X X OXOXO': [1],
'X X OOXXO': [3],
'X X OOXOX': [1, 3],
'X X OOOXX': [3],
'X OXXOOX ': [8],
'X OXX OXO': [5],
'X OXOX XO': [6],
'X OXOX OX': [1, 6],
'X OXOO XX': [6],
'X OX XOXO': [4],
'X OX XOOX': [4],
'X OX OOXX': [4],
'X OOXXXO ': [8],
'X OOXXX O': [1, 7],
'X OOXXOX ': [1, 8],
'X OOXX XO': [1],
'X OOXOXX ': [8],
'X OOX XXO': [5],
'X OOOXXX ': [8],
'X OOOXX X': [7],
'X OOOX XX': [6],
'X OO XXXO': [1, 4],
'X OO XXOX': [4],
'X OO XOXX': [4],
'X O XXXOO': [3],
'X O XXOXO': [1, 3],
'X O OXXXO': [3],
'X O OXXOX': [1],
'X  XXOOXO': [2],
'X  XOXOXO': [2],
'X  XOXOOX': [1, 2],
'X  XOOOXX': [2],
'X  OXXXOO': [2],
'X  OXXOXO': [1],
'X  OXOXXO': [2],
'X  OOXXXO': [1, 2],
'X  OOXXOX': [1],
'X  OOXOXX': [2],
'OXXXXOO  ': [7],
'OXXXXO O ': [6],
'OXXXXO  O': [6, 7],
'OXXXX OO ': [8],
'OXXXX O O': [7],
'OXXXX  OO': [6],
'OXXXOXO  ': [8],
'OXXXOX O ': [8],
'OXXXOOX  ': [8],
'OXXXOO X ': [8],
'OXXXOO  X': [6, 7],
'OXXXO XO ': [8],
'OXXXO OX ': [8],
'OXXXO O X': [5],
'OXXXO  OX': [5],
'OXXX XOO ': [8],
'OXXX XO O': [4, 7],
'OXXX X OO': [4, 6],
'OXXX OXO ': [4],
'OXXX OX O': [4],
'OXXX OOX ': [4],
'OXXX OO X': [4, 7],
'OXXX O XO': [4],
'OXXX O OX': [4, 6],
'OXXX  XOO': [4],
'OXXX  OXO': [4],
'OXXX  OOX': [5],
'OXXOXX O ': [6],
'OXXOXX  O': [6],
'OXXOXO  X': [6],
'OXXOX  OX': [6],
'OXXOOXX  ': [8],
'OXXOOX X ': [6, 8],
'OXXOO XX ': [5, 8],
'OXXOO X X': [5],
'OXXOO  XX': [5, 6],
'OXXO XXO ': [4, 8],
'OXXO XX O': [4],
'OXXO X XO': [4, 6],
'OXXO OXX ': [4],
'OXXO OX X': [4],
'OXXO O XX': [4, 6],
'OXXO  XXO': [4],
'OXXO  XOX': [4, 5],
'OXX XXOO ': [3, 8],
'OXX XXO O': [3, 7],
'OXX XX OO': [6],
'OXX XOO X': [3],
'OXX XO OX': [6],
'OXX X OOX': [3],
'OXX OXXO ': [8],
'OXX OXOX ': [3, 8],
'OXX OOXX ': [3, 8],
'OXX OOX X': [3],
'OXX OO XX': [3],
'OXX O XOX': [5],
'OXX O OXX': [3],
'OXX  XXOO': [4],
'OXX  XOXO': [3, 4],
'OXX  OXXO': [4],
'OXX  OXOX': [4],
'OXX  OOXX': [3],
'OXOXXOX  ': [8],
'OXOXXO  X': [7],
'OXOXX XO ': [5],
'OXOXX X O': [5],
'OXOXX O X': [5, 7],
'OXOXX  OX': [5],
'OXOXOXX  ': [8],
'OXOXOX X ': [6, 8],
'OXOXOX  X': [6],
'OXOXO XX ': [8],
'OXOXO X X': [7],
'OXOXO  XX': [6],
'OXOX XXO ': [4],
'OXOX XX O': [4],
'OXOX XOX ': [4],
'OXOX XO X': [4],
'OXOX X XO': [4],
'OXOX X OX': [4],
'OXOX OXX ': [8],
'OXOX OX X': [7],
'OXOX O XX': [4, 6],
'OXOX  XXO': [4, 5],
'OXOX  XOX': [4, 5],
'OXOX  OXX': [4],
'OXOOXXX  ': [7],
'OXOOXX  X': [6],
'OXOOX X X': [7],
'OXOO XXX ': [4, 8],
'OXOO XX X': [7],
'OXOO X XX': [6],
'OXO XXXO ': [3],
'OXO XXX O': [3, 7],
'OXO XXO X': [3],
'OXO XX OX': [3],
'OXO XOX X': [7],
'OXO X XOX': [3, 5],
'OXO OXXX ': [8],
'OXO OXX X': [7],
'OXO OX XX': [6],
'OXO  XXXO': [4],
'OXO  XXOX': [3, 4],
'OXO  XOXX': [3, 4],
'OX XXOXO ': [2],
'OX XXOX O': [2],
'OX XXOO X': [7],
'OX XXO OX': [2, 6],
'OX XX XOO': [2, 5],
'OX XX OOX': [5],
'OX XOXXO ': [8],
'OX XOXOX ': [2, 8],
'OX XOXO X': [2],
'OX XOX OX': [2],
'OX XOOXX ': [8],
'OX XOOX X': [7],
'OX XOO XX': [6],
'OX XO XOX': [2, 5],
'OX XO OXX': [2],
'OX X XXOO': [4],
'OX X XOXO': [4],
'OX X XOOX': [2, 4],
'OX X OXXO': [2, 4],
'OX X OXOX': [2, 4],
'OX X OOXX': [4],
'OX OXXXO ': [2],
'OX OXXX O': [2, 7],
'OX OXX OX': [6],
'OX OXOX X': [2, 7],
'OX OX XOX': [2],
'OX OOXXX ': [8],
'OX OOXX X': [2, 7],
'OX OOX XX': [6],
'OX O XXXO': [4],
'OX O XXOX': [2],
'OX  XXXOO': [2, 3],
'OX  XXOOX': [3],
'OX  XOXOX': [2],
'OX  OXXOX': [2],
'OX  OXOXX': [2, 3],
'OOXXXO X ': [6],
'OOXXXO  X': [6],
'OOXXX OX ': [5],
'OOXXX O X': [5],
'OOXXX  XO': [5, 6],
'OOXXX  OX': [5, 6],
'OOXXOXX  ': [7, 8],
'OOXXOX X ': [8],
'OOXXO XX ': [8],
'OOXXO X X': [7],
'OOXXO  XX': [5, 6],
'OOXX XXO ': [4],
'OOXX XX O': [4],
'OOXX XOX ': [4, 8],
'OOXX X XO': [4],
'OOXX OXX ': [4, 8],
'OOXX OX X': [4, 7],
'OOXX O XX': [6],
'OOXX  XXO': [4],
'OOXX  XOX': [4],
'OOXX  OXX': [5],
'OOXOXX X ': [6],
'OOXOX  XX': [6],
'OOXO XXX ': [4, 8],
'OOX XXOX ': [3],
'OOX XX XO': [3, 6],
'OOX XO XX': [6],
'OOX X OXX': [3],
'OOX OXXX ': [8],
'OOX  XXXO': [4],
'OO XXOXX ': [2],
'OO XXOX X': [2],
'OO XXO XX': [2],
'OO XX XXO': [2],
'OO XX XOX': [2],
'OO XX OXX': [2],
'OO XOXXX ': [2, 8],
'OO XOXX X': [2, 7],
'OO XOX XX': [2],
'OO X XXXO': [2, 4],
'OO X XXOX': [2, 4],
'OO X XOXX': [2],
'OO OXXXX ': [2],
'OO OXXX X': [2],
'OO OXX XX': [2, 6],
'OO  XXXXO': [2],
'OO  XXXOX': [2],
'OO  XXOXX': [2, 3],
'O XXXOOX ': [1],
'O XXXOO X': [1, 7],
'O XXXO XO': [1, 6],
'O XXXO OX': [6],
'O XXX OXO': [1, 5],
'O XXX OOX': [5],
'O XXOXXO ': [1, 8],
'O XXOXOX ': [8],
'O XXOOXX ': [8],
'O XXOOX X': [7],
'O XXOO XX': [6],
'O XXO XOX': [1],
'O XXO OXX': [5],
'O XX XXOO': [4],
'O XX XOXO': [4],
'O XX OXXO': [4],
'O XX OXOX': [4],
'O XX OOXX': [1, 4],
'O XOXX XO': [6],
'O XOXO XX': [6],
'O XOOXXX ': [8],
'O XO XXXO': [4],
'O X XXOXO': [3],
'O X XOOXX': [3],
'O OXXOXX ': [1, 8],
'O OXXOX X': [1],
'O OXXO XX': [1],
'O OXX XXO': [1, 5],
'O OXX XOX': [1],
'O OXX OXX': [1],
'O OXOXXX ': [1, 8],
'O OXOXX X': [1],
'O OXOX XX': [1, 6],
'O OX XXXO': [1, 4],
'O OX XXOX': [1],
'O OX XOXX': [1, 4],
'O OOXXXX ': [1],
'O OOXXX X': [1],
'O OOXX XX': [1, 6],
'O O XXXXO': [1],
'O O XXXOX': [1],
'O O XXOXX': [1, 3],
'O  XXOXXO': [2],
'O  XXOXOX': [2],
'O  XXOOXX': [1],
'O  XOXXOX': [1],
'O  XOXOXX': [2],
'O  OXXXXO': [1, 2],
'O  OXXXOX': [2],
' XXXXOOO ': [8],
' XXXXOO O': [7],
' XXXXO OO': [6],
' XXXOXOO ': [8],
' XXXOXO O': [0, 7],
' XXXOX OO': [0, 6],
' XXXOOXO ': [0],
' XXXOOX O': [0],
' XXXOOOX ': [0],
' XXXOOO X': [0],
' XXXOO XO': [0],
' XXXOO OX': [0],
' XXXO XOO': [0],
' XXXO OXO': [0],
' XXXO OOX': [0, 5],
' XXX OXOO': [0, 4],
' XXX OOXO': [0, 4],
' XXX OOOX': [0],
' XXOXXOO ': [0, 8],
' XXOXXO O': [0, 7],
' XXOXX OO': [6],
' XXOXOO X': [0],
' XXOXO OX': [0, 6],
' XXOX OOX': [0],
' XXOOXXO ': [0, 8],
' XXOOXX O': [0],
' XXOOXOX ': [0],
' XXOOX XO': [0],
' XXOO XXO': [0, 5],
' XXOO XOX': [5],
' XXOO OXX': [0, 5],
' XXO XXOO': [0, 4],
' XXO XOXO': [0],
' XXO OXXO': [4],
' XXO OXOX': [4],
' XXO OOXX': [0, 4],
' XX XOOOX': [0],
' XX OXXOO': [0],
' XX OXOXO': [0],
' XX OOXXO': [0, 3],
' XX OOXOX': [3],
' XX OOOXX': [3],
' XOXXOXO ': [8],
' XOXXOO X': [0, 7],
' XOXXO OX': [0],
' XOXX XOO': [5],
' XOXX OOX': [0, 5],
' XOXOXXO ': [0],
' XOXOXX O': [0],
' XOXOX XO': [0, 6],
' XOXOX OX': [6],
' XOXOOXX ': [8],
' XOXOOX X': [0, 7],
' XOXOO XX': [6],
' XOXO XXO': [0, 5],
' XOXO XOX': [0],
' XOX XXOO': [0, 4],
' XOX XOXO': [4],
' XOX XOOX': [4],
' XOX OXOX': [0],
' XOX OOXX': [4],
' XOOXXXO ': [0, 8],
' XOOXXX O': [7],
' XOOXXO X': [0],
' XOOXX OX': [0],
' XOOXOX X': [0, 7],
' XOOX XOX': [0],
' XOOOXXX ': [8],
' XOOOXX X': [7],
' XOOOX XX': [6],
' XOO XXXO': [4],
' XOO XXOX': [0, 4],
' XOO XOXX': [0, 4],
' XO XXXOO': [3],
' XO XXOOX': [0, 3],
' XO XOXOX': [0],
' XO OXXXO': [0],
' XO OXXOX': [0, 3],
' X XXOXOO': [2],
' X XXOOOX': [0],
' X XOXXOO': [0],
' X XOXOXO': [0, 2],
' X XOXOOX': [2],
' X XOOXXO': [0, 2],
' X XOOXOX': [0],
' X XOOOXX': [2],
' X OXXXOO': [2],
' X OXXOOX': [0],
' X OXOXOX': [0, 2],
' X OOXXXO': [0],
' X OOXXOX': [2],
' X OOXOXX': [0, 2],
' OXXXOOX ': [0, 8],
' OXXXOO X': [0],
' OXXXO XO': [6],
' OXXXO OX': [0, 6],
' OXXX OXO': [5],
' OXXX OOX': [0, 5],
' OXXOXX O': [0, 7],
' OXXOXOX ': [8],
' OXXOX XO': [0],
' OXXOOXX ': [0, 8],
' OXXOOX X': [7],
' OXXOO XX': [6],
' OXXO XXO': [0],
' OXXO OXX': [5],
' OXX XXOO': [4],
' OXX XOXO': [4],
' OXX OXXO': [0, 4],
' OXX OXOX': [4],
' OXX OOXX': [0, 4],
' OXOXXOX ': [0],
' OXOXX XO': [6],
' OXOXO XX': [0, 6],
' OXOX OXX': [0],
' OXOOXXX ': [8],
' OXO XXXO': [4],
' OX XXOXO': [3],
' OX XOOXX': [0],
' OX OXXXO': [0],
' OOXXOXX ': [0, 8],
' OOXXOX X': [0],
' OOXXO XX': [0],
' OOXX XXO': [0, 5],
' OOXX XOX': [0],
' OOXX OXX': [0],
' OOXOXXX ': [0],
' OOXOXX X': [0, 7],
' OOXOX XX': [0, 6],
' OOX XXXO': [0],
' OOX XXOX': [0, 4],
' OOX XOXX': [0, 4],
' OOOXXXX ': [0],
' OOOXXX X': [0],
' OOOXX XX': [0],
' OO XXXXO': [0],
' OO XXXOX': [0],
' OO XXOXX': [0],
' O XXOXXO': [2],
' O XXOXOX': [0, 2],
' O XXOOXX': [0],
' O XOXXXO': [0],
' O XOXOXX': [2],
' O OXXXXO': [2],
' O OXXXOX': [0, 2],
' O OXXOXX': [0],
'  XXXOOXO': [1],
'  XXXOOOX': [0],
'  XXOXXOO': [0, 1],
'  XXOXOXO': [0],
'  XXOOXXO': [0],
'  XXOOXOX': [1],
'  XXOOOXX': [0, 1],
'  XOXXOXO': [0],
'  XOXOOXX': [0],
'  XOOXXXO': [0],
'  OXXOXOX': [0],
'  OXXOOXX': [0, 1],
'  OXOXXXO': [0],
'  OXOXXOX': [1],
'  OOXXXXO': [1],
'  OOXXXOX': [0],
'  OOXXOXX': [0]}
